.PHONY: infra-start infra-stop infra-reset infra-logs \
        redis-cli redis-flush redis-info \
        nats-setup-streams nats-stream-list nats-stream-info \
        migrate psql psql-ingestor psql-media db-studio-ingestor db-studio-media \
        ingestor-dev ingestor-build ingestor-start ingestor-test ingestor-test-watch ingestor-format ingestor-lint ingestor-check \
        ingestor-docker-build ingestor-docker-run ingestor-docker-stop ingestor-docker-logs \
        ingestor-e2e-test ingestor-e2e-test-watch ingestor-e2e-verify \
        media-dev media-build media-start media-test media-test-watch media-format media-lint media-check \
        variant-generator-dev variant-generator-build variant-generator-start variant-generator-test variant-generator-test-watch variant-generator-format variant-generator-lint variant-generator-check \
        gateway-dev gateway-build gateway-start gateway-test gateway-test-watch gateway-format gateway-lint gateway-check \
        web-dev web-build web-preview web-format web-lint web-check web-test web-test-watch \
        react-muuri-build react-muuri-test react-muuri-test-watch react-muuri-format react-muuri-lint react-muuri-check react-muuri-storybook react-muuri-storybook-build \
        docs-dev docs-build docs-start \
        openapi-generate docs-generate openapi-verify \
        worktree-remove \
        dev build test test-watch test-unit test-integration test-e2e test-ui coverage-summary format lint check-types ci ci-force clean help

# ─── Worktree-Aware Variables ────────────────────────────────────────────────
# Load .worktree if it exists (generated by scripts/setup-worktree.mjs via pnpm install).
# Variables from .worktree override the defaults below.
-include .worktree

COMPOSE_PROJECT_NAME ?= wallpaperdb
INGRESS_PORT         ?= 8000
POSTGRES_HOST_PORT   ?= 8001
MINIO_API_HOST_PORT  ?= 8002
NATS_HOST_PORT       ?= 8003
REDIS_HOST_PORT      ?= 8004
OPENSEARCH_HOST_PORT ?= 8005
OTEL_HTTP_HOST_PORT  ?= 8006
OTEL_GRPC_HOST_PORT  ?= 8007

export COMPOSE_PROJECT_NAME
export INGRESS_PORT

# Convenience shorthand for all infra docker compose commands.
# Uses deferred expansion (=) so COMPOSE_PROJECT_NAME is resolved at use time.
INFRA_COMPOSE = docker compose -p $(COMPOSE_PROJECT_NAME) -f infra/docker-compose.yml
APPS_COMPOSE  = docker compose -p $(COMPOSE_PROJECT_NAME) -f infra/docker-compose.apps.yml

help:
	@echo "WallpaperDB - Available commands:"
	@echo ""
	@echo "Current worktree: project=$(COMPOSE_PROJECT_NAME), ingress=http://localhost:$(INGRESS_PORT)"
	@echo ""
	@echo "Infrastructure:"
	@echo "  make infra-start    - Start all infrastructure services"
	@echo "  make infra-stop     - Stop all infrastructure services"
	@echo "  make infra-reset    - Reset all infrastructure data (WARNING: deletes all data)"
	@echo "  make infra-logs     - Tail logs from all infrastructure services"
	@echo ""
	@echo "Redis:"
	@echo "  make redis-cli      - Connect to Redis CLI"
	@echo "  make redis-flush    - Flush all Redis data (WARNING: deletes all data)"
	@echo "  make redis-info     - Show Redis server info"
	@echo ""
	@echo "NATS:"
	@echo "  make nats-setup-streams - Setup all required NATS JetStream streams"
	@echo "  make nats-stream-list   - List all NATS streams"
	@echo "  make nats-stream-info   - Show info for WALLPAPER stream"
	@echo ""
	@echo "Database:"
	@echo "  make migrate            - Run database migrations (apply to local infra)"
	@echo "  make psql               - Open psql shell (default database)"
	@echo "  make psql-ingestor      - Open psql shell (wallpaperdb_ingestor database)"
	@echo "  make psql-media         - Open psql shell (wallpaperdb_media database)"
	@echo "  make db-studio-ingestor - Start Drizzle Studio for ingestor"
	@echo "  make db-studio-media    - Start Drizzle Studio for media"
	@echo ""
	@echo "Ingestor Service:"
	@echo "  make ingestor-dev        - Start ingestor in development mode"
	@echo "  make ingestor-build      - Build ingestor for production"
	@echo "  make ingestor-start      - Start ingestor in production mode"
	@echo "  make ingestor-test       - Run ingestor tests"
	@echo "  make ingestor-test-watch - Run ingestor tests in watch mode"
	@echo "  make ingestor-format     - Format ingestor code"
	@echo "  make ingestor-lint       - Lint ingestor code"
	@echo ""
	@echo "Media Service:"
	@echo "  make media-dev        - Start media service in development mode"
	@echo "  make media-build      - Build media service for production"
	@echo "  make media-start      - Start media service in production mode"
	@echo "  make media-test       - Run media service tests"
	@echo "  make media-test-watch - Run media service tests in watch mode"
	@echo "  make media-format     - Format media service code"
	@echo "  make media-lint       - Lint media service code"
	@echo ""
	@echo "Variant Generator Service:"
	@echo "  make variant-generator-dev        - Start variant-generator in development mode"
	@echo "  make variant-generator-build      - Build variant-generator for production"
	@echo "  make variant-generator-start      - Start variant-generator in production mode"
	@echo "  make variant-generator-test       - Run variant-generator tests"
	@echo "  make variant-generator-test-watch - Run variant-generator tests in watch mode"
	@echo "  make variant-generator-format     - Format variant-generator code"
	@echo "  make variant-generator-lint       - Lint variant-generator code"
	@echo ""
	@echo "Gateway Service:"
	@echo "  make gateway-dev        - Start gateway service in development mode"
	@echo "  make gateway-build      - Build gateway service for production"
	@echo "  make gateway-start      - Start gateway service in production mode"
	@echo "  make gateway-test       - Run gateway service tests"
	@echo "  make gateway-test-watch - Run gateway service tests in watch mode"
	@echo "  make gateway-format     - Format gateway service code"
	@echo "  make gateway-lint       - Lint gateway service code"
	@echo ""
	@echo "Web Frontend:"
	@echo "  make web-dev        - Start web frontend in development mode"
	@echo "  make web-build      - Build web frontend for production"
	@echo "  make web-preview    - Preview production build"
	@echo "  make web-test       - Run web frontend tests"
	@echo "  make web-test-watch - Run web frontend tests in watch mode"
	@echo "  make web-format     - Format web frontend code"
	@echo "  make web-lint       - Lint web frontend code"
	@echo "  make web-check      - Type check web frontend"
	@echo ""
	@echo "React Muuri Package:"
	@echo "  make react-muuri-build          - Build react-muuri package"
	@echo "  make react-muuri-test           - Run react-muuri tests"
	@echo "  make react-muuri-test-watch     - Run react-muuri tests in watch mode"
	@echo "  make react-muuri-format         - Format react-muuri code"
	@echo "  make react-muuri-lint           - Lint react-muuri code"
	@echo "  make react-muuri-check          - Type check react-muuri"
	@echo "  make react-muuri-storybook      - Start Storybook dev server (http://localhost:6006)"
	@echo "  make react-muuri-storybook-build - Build Storybook for production"
	@echo ""
	@echo "Ingestor Docker:"
	@echo "  make ingestor-docker-build - Build ingestor Docker image"
	@echo "  make ingestor-docker-run   - Run ingestor Docker container (uses infra/.env)"
	@echo "  make ingestor-docker-stop  - Stop ingestor Docker container"
	@echo "  make ingestor-docker-logs  - View ingestor Docker container logs"
	@echo ""
	@echo "Ingestor E2E Tests:"
	@echo "  make ingestor-e2e-test       - Run E2E tests against Docker container"
	@echo "  make ingestor-e2e-test-watch - Run E2E tests in watch mode"
	@echo "  make ingestor-e2e-verify     - Verify no app code imports in E2E tests"
	@echo ""
	@echo "Documentation:"
	@echo "  make docs-dev       - Start documentation dev server (http://localhost:3002)"
	@echo "  make docs-build     - Build documentation for production"
	@echo "  make docs-start     - Start documentation production server"
	@echo ""
	@echo "OpenAPI:"
	@echo "  make openapi-generate - Generate OpenAPI specs (swagger.json) for all services"
	@echo "  make docs-generate    - Generate API documentation from OpenAPI specs"
	@echo "  make openapi-verify   - Verify OpenAPI specs can be generated"
	@echo ""
	@echo "Worktree:"
	@echo "  make worktree-remove - Tear down this worktree's containers and release its slot"
	@echo ""
	@echo "All Services:"
	@echo "  make dev        - Start all services in development mode"
	@echo "  make build      - Build all services"
	@echo "  make test       - Run all tests"
	@echo "  make test-watch - Run all tests in watch mode"
	@echo "  make format     - Format all code"
	@echo "  make lint       - Lint all code"
	@echo ""
	@echo "Testing (by intensity):"
	@echo "  make test-unit         - Run unit tests (fast, no containers)"
	@echo "  make test-integration  - Run integration tests (uses Testcontainers)"
	@echo "  make test-e2e          - Run E2E tests (heavy container usage, sequential)"
	@echo "  make test-ui           - Run tests with Vitest UI"
	@echo "  make coverage-summary  - Display AI-friendly coverage summary"
	@echo ""
	@echo "CI/Local Parity:"
	@echo "  make ci                - Run full CI pipeline locally"
	@echo "  make ci-force          - Run full CI pipeline (skip turbo cache)"
	@echo "  make check-types       - Run type checking on all packages"
	@echo ""
	@echo "Cleanup:"
	@echo "  make clean             - Remove all generated artifacts (node_modules, caches, build output)"
	@echo ""

infra-start:
	@$(INFRA_COMPOSE) up -d
	@echo ""
	@echo "Infrastructure started. Project: $(COMPOSE_PROJECT_NAME)"
	@echo ""
	@echo "Service endpoints:"
	@echo "  Postgres:    localhost:$(POSTGRES_HOST_PORT)"
	@echo "  MinIO API:   http://localhost:$(MINIO_API_HOST_PORT)"
	@echo "  NATS:        nats://localhost:$(NATS_HOST_PORT)"
	@echo "  Redis:       localhost:$(REDIS_HOST_PORT)"
	@echo "  OpenSearch:  http://localhost:$(OPENSEARCH_HOST_PORT)"
	@echo "  OTEL HTTP:   http://localhost:$(OTEL_HTTP_HOST_PORT)"
	@echo "  OTEL gRPC:   localhost:$(OTEL_GRPC_HOST_PORT)"
	@echo ""
	@echo "Admin UIs available via Caddy ingress at http://localhost:$(INGRESS_PORT)"
	@echo "  Grafana:             /grafana"
	@echo "  MinIO Console:       /minio"
	@echo "  pgAdmin:              /pgadmin"
	@echo "  OpenSearch Dashboards: /opensearch-dashboards"
	@echo "  NATS Monitoring:     /nats"

infra-stop:
	@$(INFRA_COMPOSE) down

infra-reset:
	@echo "WARNING: This will delete all data for project $(COMPOSE_PROJECT_NAME)!"
	@read -p "Are you sure? (yes/no): " REPLY && \
		[ "$$REPLY" = "yes" ] || { echo "Reset cancelled."; exit 1; }
	@$(INFRA_COMPOSE) down -v
	@echo "Infrastructure reset complete!"

infra-logs:
	@$(INFRA_COMPOSE) logs -f

# Redis commands
redis-cli:
	@$(INFRA_COMPOSE) exec redis redis-cli

redis-flush:
	@$(INFRA_COMPOSE) exec redis redis-cli FLUSHALL

redis-info:
	@$(INFRA_COMPOSE) exec redis redis-cli INFO

# NATS commands
nats-setup-streams:
	@NATS_SERVER=nats://localhost:$(NATS_HOST_PORT) ./infra/nats/init/setup-streams.sh

nats-stream-list:
	@nats stream list --server nats://localhost:$(NATS_HOST_PORT)

nats-stream-info:
	@nats stream info WALLPAPER --server nats://localhost:$(NATS_HOST_PORT)

# Database commands
migrate:
	@echo "Running database migrations..."
	@turbo run db:migrate
	@echo "✓ Database migrations completed"

psql:
	@$(INFRA_COMPOSE) exec postgres psql -U wallpaperdb

psql-ingestor:
	@$(INFRA_COMPOSE) exec postgres psql -U wallpaperdb -d wallpaperdb_ingestor

psql-media:
	@$(INFRA_COMPOSE) exec postgres psql -U wallpaperdb -d wallpaperdb_media

db-studio-ingestor:
	@pnpm --filter @wallpaperdb/ingestor db:studio

db-studio-media:
	@pnpm --filter @wallpaperdb/media db:studio

# Ingestor service commands
ingestor-dev:
	@turbo run dev --filter=@wallpaperdb/ingestor

ingestor-build:
	@turbo run build --filter=@wallpaperdb/ingestor

ingestor-start:
	@turbo run start --filter=@wallpaperdb/ingestor

ingestor-test:
	@turbo run test --filter=@wallpaperdb/ingestor

ingestor-test-watch:
	@turbo run test:watch --filter=@wallpaperdb/ingestor

ingestor-format:
	@turbo run format --filter=@wallpaperdb/ingestor

ingestor-lint:
	@turbo run lint --filter=@wallpaperdb/ingestor

ingestor-check:
	@turbo run check --filter=@wallpaperdb/ingestor

# Media service commands
media-dev:
	@turbo run dev --filter=@wallpaperdb/media

media-build:
	@turbo run build --filter=@wallpaperdb/media

media-start:
	@turbo run start --filter=@wallpaperdb/media

media-test:
	@turbo run test --filter=@wallpaperdb/media

media-test-watch:
	@turbo run test:watch --filter=@wallpaperdb/media

media-format:
	@turbo run format --filter=@wallpaperdb/media

media-lint:
	@turbo run lint --filter=@wallpaperdb/media

media-check:
	@turbo run check --filter=@wallpaperdb/media

# Variant Generator service commands
variant-generator-dev:
	@turbo run dev --filter=@wallpaperdb/variant-generator

variant-generator-build:
	@turbo run build --filter=@wallpaperdb/variant-generator

variant-generator-start:
	@turbo run start --filter=@wallpaperdb/variant-generator

variant-generator-test:
	@turbo run test --filter=@wallpaperdb/variant-generator

variant-generator-test-watch:
	@turbo run test:watch --filter=@wallpaperdb/variant-generator

variant-generator-format:
	@turbo run format --filter=@wallpaperdb/variant-generator

variant-generator-lint:
	@turbo run lint --filter=@wallpaperdb/variant-generator

variant-generator-check:
	@turbo run check --filter=@wallpaperdb/variant-generator

# Gateway service commands
gateway-dev:
	@turbo run dev --filter=@wallpaperdb/gateway

gateway-build:
	@turbo run build --filter=@wallpaperdb/gateway

gateway-start:
	@turbo run start --filter=@wallpaperdb/gateway

gateway-test:
	@turbo run test --filter=@wallpaperdb/gateway

gateway-test-watch:
	@turbo run test:watch --filter=@wallpaperdb/gateway

gateway-format:
	@turbo run format --filter=@wallpaperdb/gateway

gateway-lint:
	@turbo run lint --filter=@wallpaperdb/gateway

gateway-check:
	@turbo run check --filter=@wallpaperdb/gateway

# Web frontend commands
web-dev:
	@turbo run dev --filter=@wallpaperdb/web

web-build:
	@turbo run build --filter=@wallpaperdb/web

web-preview:
	@turbo run preview --filter=@wallpaperdb/web

web-format:
	@turbo run format --filter=@wallpaperdb/web

web-lint:
	@turbo run lint --filter=@wallpaperdb/web

web-check:
	@turbo run check-types --filter=@wallpaperdb/web

web-test:
	@turbo run test --filter=@wallpaperdb/web

web-test-watch:
	@pnpm --filter @wallpaperdb/web test:watch

# React Muuri package commands
react-muuri-build:
	@turbo run build --filter=@wallpaperdb/react-muuri

react-muuri-test:
	@turbo run test --filter=@wallpaperdb/react-muuri

react-muuri-test-watch:
	@pnpm --filter @wallpaperdb/react-muuri test:watch

react-muuri-format:
	@turbo run format --filter=@wallpaperdb/react-muuri

react-muuri-lint:
	@turbo run lint --filter=@wallpaperdb/react-muuri

react-muuri-check:
	@turbo run check-types --filter=@wallpaperdb/react-muuri

react-muuri-storybook:
	@pnpm --filter @wallpaperdb/react-muuri storybook

react-muuri-storybook-build:
	@pnpm --filter @wallpaperdb/react-muuri build-storybook

# Ingestor Docker commands
ingestor-docker-build:
	@echo "Building ingestor Docker image..."
	@docker build -t $(COMPOSE_PROJECT_NAME)-ingestor:latest -f apps/ingestor/Dockerfile .
	@echo "✓ Docker image built: $(COMPOSE_PROJECT_NAME)-ingestor:latest"

ingestor-docker-run:
	@echo "Starting ingestor Docker container..."
	@if [ ! -f infra/.env ]; then \
		echo "Error: infra/.env file not found. Run 'make infra-start' first."; \
		exit 1; \
	fi
	@. ./infra/.env && docker run --rm -d \
		-p 3001:3001 \
		-e NODE_ENV=production \
		-e PORT=3001 \
		-e DATABASE_URL=postgresql://$$POSTGRES_USER:$$POSTGRES_PASSWORD@host.docker.internal:$(POSTGRES_HOST_PORT)/$$POSTGRES_DB \
		-e S3_ENDPOINT=http://host.docker.internal:$(MINIO_API_HOST_PORT) \
		-e S3_ACCESS_KEY_ID=$$MINIO_ROOT_USER \
		-e S3_SECRET_ACCESS_KEY=$$MINIO_ROOT_PASSWORD \
		-e S3_BUCKET=wallpapers \
		-e NATS_URL=nats://host.docker.internal:$(NATS_HOST_PORT) \
		-e OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:$(OTEL_HTTP_HOST_PORT) \
		--name $(COMPOSE_PROJECT_NAME)-ingestor \
		$(COMPOSE_PROJECT_NAME)-ingestor:latest
	@echo "✓ Ingestor container started"
	@echo "  Health: http://localhost:$(INGRESS_PORT)/ingestor/health"
	@echo "  Ready:  http://localhost:$(INGRESS_PORT)/ingestor/ready"

ingestor-docker-stop:
	@echo "Stopping ingestor Docker container..."
	@docker stop $(COMPOSE_PROJECT_NAME)-ingestor 2>/dev/null || echo "Container not running"
	@echo "✓ Ingestor container stopped"

ingestor-docker-logs:
	@docker logs -f $(COMPOSE_PROJECT_NAME)-ingestor

# Ingestor E2E test commands
ingestor-e2e-test:
	@echo "Running E2E tests (builds Docker image first)..."
	@turbo run test --filter=@wallpaperdb/ingestor-e2e

ingestor-e2e-test-watch:
	@turbo run test:watch --filter=@wallpaperdb/ingestor-e2e

ingestor-e2e-verify:
	@echo "Verifying E2E tests don't import application code..."
	@pnpm --filter @wallpaperdb/ingestor-e2e verify-no-imports
	@echo "✓ Verification passed - E2E tests are properly isolated"

# Documentation commands
docs-dev:
	@echo "Starting documentation dev server..."
	@turbo run dev --filter=@wallpaperdb/docs

docs-build:
	@echo "Building documentation..."
	@turbo run build --filter=@wallpaperdb/docs

docs-start:
	@echo "Starting documentation production server..."
	@turbo run start --filter=@wallpaperdb/docs

# OpenAPI commands
openapi-generate:
	@echo "Generating OpenAPI specs..."
	@pnpm --filter @wallpaperdb/ingestor gen:swagger
	@echo "✓ OpenAPI spec generated: apps/ingestor/swagger.json"

docs-generate:
	@echo "Generating API documentation from OpenAPI specs..."
	@pnpm --filter @wallpaperdb/docs gen:swagger-pages
	@echo "✓ API documentation generated in apps/docs/content/docs/openapi/"

openapi-verify:
	@echo "Verifying OpenAPI spec generation..."
	@pnpm --filter @wallpaperdb/ingestor gen:swagger
	@if [ -f apps/ingestor/swagger.json ]; then \
		echo "✓ OpenAPI spec generated successfully"; \
	else \
		echo "✗ Failed to generate OpenAPI spec"; \
		exit 1; \
	fi

worktree-remove:
	@node scripts/teardown-worktree.mjs

# All services commands
dev:
	@scripts/check-infra.sh || \
	  (echo "Infra is not running. Start it first with: make infra-start" && exit 1)
	@$(APPS_COMPOSE) watch

build:
	@turbo run build

test:
	@turbo run test

test-watch:
	@turbo run test:watch

# Test commands by intensity
test-unit:
	@echo "Running unit tests (fast, no containers)..."
	@turbo run test:unit

test-integration:
	@echo "Running integration tests (uses Testcontainers)..."
	@turbo run test:integration --concurrency=1

test-e2e:
	@echo "Running E2E tests (heavy container usage, sequential)..."
	@turbo run test:e2e --concurrency=1

test-ui:
	@echo "Starting Vitest UI..."
	@pnpm test:ui

coverage-summary:
	@node scripts/coverage-summary.js

format:
	@turbo run format --log-order grouped

lint:
	@turbo run lint --log-order grouped

lint-fix:
	@turbo run lint:fix --log-order grouped

check:
	@turbo run build lint check-types --log-order grouped

install:
	pnpm install

# CI/Local Parity commands
check-types:
	@turbo run check-types

# CI/Local Parity commands
check-types-force:
	@turbo run check-types --force

ci:
	@echo "Running full CI checks locally..."
	@start_time=$$(date +%s); \
	turbo run build lint check-types test:unit test:integration && \
	turbo run test:e2e --concurrency=1 && \
	pnpm coverage:merge && \
	end_time=$$(date +%s); \
	duration=$$((end_time - start_time)); \
	echo ""; \
	echo "✓ All CI checks passed in $${duration}s"; \
	echo "✓ Coverage report: coverage/lcov.info"

ci-force:
	@echo "Running full CI checks locally (no cache)..."
	@start_time=$$(date +%s); \
	turbo run build lint check-types test:unit test:integration --force && \
	turbo run test:e2e --concurrency=1 --force && \
	pnpm coverage:merge && \
	end_time=$$(date +%s); \
	duration=$$((end_time - start_time)); \
	echo ""; \
	echo "✓ All CI checks passed in $${duration}s"; \
	echo "✓ Coverage report: coverage/lcov.info"

# Clean generated artifacts
clean:
	@echo "Cleaning node_modules..."
	@rm -rf node_modules apps/*/node_modules packages/*/node_modules experiments/*/node_modules
	@echo "Cleaning compiled output..."
	@rm -rf apps/*/dist apps/docs/.next packages/*/dist packages/react-muuri/storybook-static
	@echo "Cleaning turbo caches..."
	@rm -rf .turbo apps/*/.turbo packages/*/.turbo
	@echo "Cleaning coverage reports..."
	@rm -rf coverage apps/*/coverage packages/*/coverage
	@echo "Cleaning TypeScript incremental build cache..."
	@find . -name "*.tsbuildinfo" -not -path "*/node_modules/*" -delete
	@echo "Cleaning generated OpenAPI specs..."
	@rm -f apps/ingestor/swagger.json apps/media/swagger.json
	@echo "✓ Clean complete"
