.DEFAULT_GOAL := help

# ─── Worktree-Aware Variables ────────────────────────────────────────────────
# Load .worktree if it exists (generated by scripts/setup-worktree.mjs via pnpm install).
# Variables from .worktree override the defaults below.
-include .worktree

COMPOSE_PROJECT_NAME ?= wallpaperdb
INGRESS_PORT         ?= 8000
POSTGRES_HOST_PORT   ?= 8001
S3_API_HOST_PORT     ?= 8002
NATS_HOST_PORT       ?= 8003
REDIS_HOST_PORT      ?= 8004
OPENSEARCH_HOST_PORT ?= 8005
OTEL_HTTP_HOST_PORT  ?= 8006
OTEL_GRPC_HOST_PORT  ?= 8007

export COMPOSE_PROJECT_NAME
export INGRESS_PORT
export CRAP_THRESHOLD

# Convenience shorthand for all infra docker compose commands.
# Uses deferred expansion (=) so COMPOSE_PROJECT_NAME is resolved at use time.
INFRA_COMPOSE = docker compose -p $(COMPOSE_PROJECT_NAME) -f infra/docker-compose.yml
APPS_COMPOSE  = docker compose -p $(COMPOSE_PROJECT_NAME) -f infra/docker-compose.apps.yml

SANDCASTLE_AUTH_DIR ?= .sandcastle
SANDCASTLE_OPENCODE_AUTH ?= $(HOME)/.local/share/opencode/auth.json
GITHUB_CLI ?= gh
TURBO := "$(CURDIR)/node_modules/.bin/turbo"
CI_CONCURRENCY ?= 1

# PACKAGE is a workspace basename; SERVICE selects a Compose app; DB selects a database.
PACKAGE ?=
SERVICE ?=
DB ?=
SCRIPT ?=
ARGS ?=
FORCE ?=
WORKSPACES := $(notdir $(patsubst %/,%,$(dir $(wildcard apps/*/package.json packages/*/package.json))))
ifneq ($(strip $(PACKAGE)),)
ifneq ($(words $(PACKAGE)),1)
$(error PACKAGE must select exactly one workspace)
endif
ifneq ($(filter-out $(WORKSPACES),$(PACKAGE)),)
$(error Unknown PACKAGE '$(PACKAGE)'. Use a workspace directory name, e.g. web or ingestor)
endif
endif
FILTER = $(if $(PACKAGE),--filter=@wallpaperdb/$(PACKAGE))
TURBO_FLAGS = $(FILTER) $(if $(filter 1,$(FORCE)),--force)

.PHONY: help install dev build test test-unit test-integration test-e2e test-focused \
        format lint lint-fix check-types check run \
        infra-start infra-stop infra-reset infra-logs apps-start apps-stop apps-build apps-logs \
        migrate psql redis-cli redis-flush redis-info nats-setup-streams nats-stream-list nats-stream-info nats-stream-setup-test \
        storage-test storage-infra-test coverage-summary crap check-crap crap-check-types \
        worktree-remove worktree-env-test sandcastle-auth sandcastle-test sandcastle-check-types test-make ci clean

help: ## Show commands and selectors
	@echo "WallpaperDB — project=$(COMPOSE_PROJECT_NAME), ingress=http://localhost:$(INGRESS_PORT)"
	@echo "Usage: make build PACKAGE=web | make apps-start SERVICE=ingestor | make psql DB=media"
	@echo "Workspace tasks default to all packages. FORCE=1 bypasses Turbo cache."
	@echo "One-off scripts: make run PACKAGE=web SCRIPT=preview ARGS='--host 0.0.0.0'"
	@echo ""
	@awk 'BEGIN {FS = ":.*## "} /^[a-z][a-z0-9-]*:.*## / {printf "  %-22s %s\n", $$1, $$2}' Makefile

install: ## Install dependencies and initialize this worktree
	pnpm install

dev: ## Watch all app containers, or one workspace with PACKAGE
ifneq ($(strip $(PACKAGE)),)
	@$(TURBO) run dev $(FILTER)
else
	@scripts/check-infra.sh || (echo "Start infrastructure with: make infra-start" && exit 1)
	@$(APPS_COMPOSE) watch
endif

build: ## Build workspaces (optional PACKAGE)
	@$(TURBO) run build $(TURBO_FLAGS)

test: ## Run workspace test scripts (optional PACKAGE)
	@$(TURBO) run test $(TURBO_FLAGS)

test-focused: ## Build dependencies and run selected tests serially (requires PACKAGE; optional ARGS)
	$(if $(PACKAGE),,$(error test-focused requires PACKAGE, e.g. make test-focused PACKAGE=web))
	@$(TURBO) run build --filter="@wallpaperdb/$(PACKAGE)^..." --concurrency=1
	@pnpm --filter @wallpaperdb/$(PACKAGE) exec vitest run --maxWorkers=1 --minWorkers=1 --no-file-parallelism $(ARGS)

test-unit: ## Run unit tests (no containers; optional PACKAGE)
	@$(TURBO) run test:unit $(TURBO_FLAGS)

test-integration: ## Run integration tests (Docker required) (optional PACKAGE)
	@$(TURBO) run test:integration $(TURBO_FLAGS) --concurrency=1

test-e2e: ## Run end-to-end tests (Docker required) (optional PACKAGE)
	@$(TURBO) run test:e2e $(TURBO_FLAGS) --concurrency=1

format: ## Format workspace code (optional PACKAGE)
	@$(TURBO) run format $(TURBO_FLAGS) --log-order grouped

lint: ## Lint workspace code (optional PACKAGE)
	@$(TURBO) run lint $(TURBO_FLAGS) --log-order grouped

lint-fix: ## Fix workspace lint issues (optional PACKAGE)
	@$(TURBO) run lint:fix $(TURBO_FLAGS) --log-order grouped

check-types: $(if $(PACKAGE),,crap-check-types) ## Type-check workspaces and root tooling (optional PACKAGE)
	@$(TURBO) run check-types $(TURBO_FLAGS)

check: $(if $(PACKAGE),,crap-check-types) ## Build, lint, and type-check (optional PACKAGE)
	@$(TURBO) run build lint check-types $(TURBO_FLAGS) --log-order grouped

run: ## Run a package.json script (requires PACKAGE and SCRIPT; optional ARGS)
	$(if $(PACKAGE),,$(error run requires PACKAGE, e.g. make run PACKAGE=web SCRIPT=preview))
	$(if $(SCRIPT),,$(error run requires SCRIPT, e.g. make run PACKAGE=web SCRIPT=preview))
	@pnpm --filter @wallpaperdb/$(PACKAGE) run $(SCRIPT) $(ARGS)

infra-start: ## Start infrastructure
	@$(INFRA_COMPOSE) up -d
	@echo ""
	@echo "Infrastructure started. Project: $(COMPOSE_PROJECT_NAME)"
	@echo ""
	@echo "Service endpoints:"
	@echo "  Postgres:    localhost:$(POSTGRES_HOST_PORT)"
	@echo "  SeaweedFS S3: http://localhost:$(S3_API_HOST_PORT)"
	@echo "  NATS:        nats://localhost:$(NATS_HOST_PORT)"
	@echo "  Redis:       localhost:$(REDIS_HOST_PORT)"
	@echo "  OpenSearch:  http://localhost:$(OPENSEARCH_HOST_PORT)"
	@echo "  OTEL HTTP:   http://localhost:$(OTEL_HTTP_HOST_PORT)"
	@echo "  OTEL gRPC:   localhost:$(OTEL_GRPC_HOST_PORT)"
	@echo ""
	@echo "Admin UIs available via Caddy ingress at http://localhost:$(INGRESS_PORT)"
	@echo "  Grafana:             /grafana"
	@echo "  pgAdmin:              /pgadmin"
	@echo "  OpenSearch Dashboards: /opensearch-dashboards"
	@echo "  NATS Monitoring:     /nats"

infra-stop: ## Stop infrastructure
	@$(INFRA_COMPOSE) down

infra-reset: ## Delete infrastructure data after confirmation
	@echo "WARNING: This will delete all data for project $(COMPOSE_PROJECT_NAME)!"
	@read -p "Are you sure? (yes/no): " REPLY && \
		[ "$$REPLY" = "yes" ] || { echo "Reset cancelled."; exit 1; }
	@$(INFRA_COMPOSE) down -v
	@echo "Infrastructure reset complete!"

infra-logs: ## Follow infrastructure logs
	@$(INFRA_COMPOSE) logs -f

apps-start: ## Build and start app containers (optional SERVICE)
	@$(APPS_COMPOSE) up -d --build $(SERVICE)

apps-stop: ## Stop apps; tear down app stack when SERVICE is omitted
	@$(APPS_COMPOSE) $(if $(SERVICE),stop $(SERVICE),down)

apps-build: ## Build development app images (optional SERVICE)
	@$(APPS_COMPOSE) build $(SERVICE)

apps-logs: ## Follow app logs (optional SERVICE)
	@$(APPS_COMPOSE) logs -f $(SERVICE)

migrate: ## Apply database migrations (optional PACKAGE)
	@$(TURBO) run db:migrate $(FILTER)

psql: ## Open PostgreSQL shell (optional DB=ingestor/media/tags/user)
	@$(INFRA_COMPOSE) exec postgres psql -U wallpaperdb $(if $(DB),-d wallpaperdb_$(DB))

redis-cli: ## Open Redis CLI
	@$(INFRA_COMPOSE) exec redis redis-cli

redis-flush: ## Delete all Redis data
	@$(INFRA_COMPOSE) exec redis redis-cli FLUSHALL

redis-info: ## Show Redis info
	@$(INFRA_COMPOSE) exec redis redis-cli INFO

nats-setup-streams: ## Initialize NATS streams
	@NATS_SERVER=nats://localhost:$(NATS_HOST_PORT) ./infra/nats/init/setup-streams.sh

nats-stream-setup-test: ## Verify stream creation and retention upgrades
	@pnpm exec vitest run infra/nats/init/setup-streams.test.ts --maxWorkers=1 --no-file-parallelism

nats-stream-list: ## List NATS streams
	@nats stream list --server nats://localhost:$(NATS_HOST_PORT)

nats-stream-info: ## Inspect WALLPAPER stream
	@nats stream info WALLPAPER --server nats://localhost:$(NATS_HOST_PORT)

storage-test: ## Test S3 compatibility against SeaweedFS
	@$(TURBO) run build --filter='@wallpaperdb/test-utils^...'
	@pnpm --filter @wallpaperdb/test-utils test tests/s3.test.ts

storage-infra-test: ## Test storage config, auth, bootstrap, and persistence
	@node --test scripts/lib/env-pipeline.test.mjs
	@node scripts/test-object-storage.mjs

coverage-summary: ## Summarize existing test coverage
	@node scripts/coverage-summary.js

crap: ## Rank functions using existing test coverage
	@pnpm exec tsx scripts/crap.mts report

check-crap: ## Check CRAP scores (requires CRAP_THRESHOLD)
	@pnpm exec tsx scripts/crap.mts check

crap-check-types: ## Type-check CRAP tooling
	@pnpm crap:check-types

worktree-remove: ## Tear down this worktree and release its slot
	@node scripts/teardown-worktree.mjs

sandcastle-auth: ## Refresh local Sandcastle credentials
	@if ! command -v "$(GITHUB_CLI)" >/dev/null 2>&1; then \
		echo "GitHub CLI not found. Install 'gh' and run 'gh auth login' first."; \
		exit 1; \
	fi
	@if [ ! -f "$(SANDCASTLE_OPENCODE_AUTH)" ]; then \
		echo "OpenCode auth not found at $(SANDCASTLE_OPENCODE_AUTH). Sign in to OpenCode first."; \
		exit 1; \
	fi
	@github_token="$$( "$(GITHUB_CLI)" auth token )" || { \
		echo "Unable to read GitHub credentials. Run 'gh auth login' first."; \
		exit 1; \
	}; \
	if [ -z "$$github_token" ]; then \
		echo "GitHub CLI returned an empty token. Run 'gh auth login' first."; \
		exit 1; \
	fi; \
	umask 077; \
	mkdir -p "$(SANDCASTLE_AUTH_DIR)/.opencode"; \
	printf 'GH_TOKEN=%s\n' "$$github_token" > "$(SANDCASTLE_AUTH_DIR)/.env"; \
	cp "$(SANDCASTLE_OPENCODE_AUTH)" "$(SANDCASTLE_AUTH_DIR)/.opencode/auth.json"; \
	chmod 600 "$(SANDCASTLE_AUTH_DIR)/.env" "$(SANDCASTLE_AUTH_DIR)/.opencode/auth.json"; \
	echo "Sandcastle credentials refreshed in $(SANDCASTLE_AUTH_DIR)."

sandcastle-test: ## Test Sandcastle runner
	@pnpm sandcastle:test

sandcastle-check-types: ## Type-check Sandcastle runner
	@pnpm sandcastle:check-types

test-make: ## Test command routing without starting services
	@node --test scripts/makefile.test.mjs

worktree-env-test: ## Verify generated service credentials and environment rules
	@pnpm exec vitest run scripts/lib/env-pipeline.test.ts --maxWorkers=1 --no-file-parallelism

ci: test-make crap-check-types ## Run full CI pipeline (FORCE=1 bypasses cache; always all packages)
	@$(MAKE) worktree-env-test
	@$(MAKE) nats-stream-setup-test
	@$(MAKE) sandcastle-test
	@$(MAKE) sandcastle-check-types
	@$(MAKE) storage-infra-test
	@echo "Running full CI checks locally..."
	@set -e; \
	start_time=$$(date +%s); \
	$(TURBO) run build lint check-types test:unit test:integration --concurrency=$(CI_CONCURRENCY) $(if $(filter 1,$(FORCE)),--force); \
	$(TURBO) run test:e2e --concurrency=1 $(if $(filter 1,$(FORCE)),--force); \
	pnpm coverage:merge; \
	end_time=$$(date +%s); \
	duration=$$((end_time - start_time)); \
	echo ""; \
	echo "✓ All CI checks passed in $${duration}s"; \
	echo "✓ Coverage report: coverage/lcov.info"

clean: ## Remove dependencies, build output, caches, and coverage
	@echo "Cleaning node_modules..."
	@rm -rf node_modules apps/*/node_modules packages/*/node_modules experiments/*/node_modules
	@echo "Cleaning compiled output..."
	@rm -rf apps/*/dist apps/docs/.next packages/*/dist packages/react-muuri/storybook-static
	@echo "Cleaning turbo caches..."
	@rm -rf .turbo apps/*/.turbo packages/*/.turbo
	@echo "Cleaning coverage reports..."
	@rm -rf coverage apps/*/coverage packages/*/coverage
	@echo "Cleaning TypeScript incremental build cache..."
	@find . -name "*.tsbuildinfo" -not -path "*/node_modules/*" -delete
	@echo "Cleaning generated OpenAPI specs..."
	@rm -f apps/ingestor/swagger.json apps/media/swagger.json apps/user/swagger.json
	@echo "✓ Clean complete"
