.PHONY: color-benchmark color-benchmark-up color-benchmark-down color-benchmark-corpus color-benchmark-diagnose color-benchmark-report color-benchmark-serve color-benchmark-extract color-benchmark-rank color-benchmark-blind-review color-benchmark-analysis color-benchmark-format \
        color-proportions color-proportions-prepare color-proportions-diagnose color-proportions-evaluate color-proportions-audit color-proportions-serve color-proportions-format \
        color-ranges color-ranges-diagnose color-ranges-evaluate color-ranges-format color-ranges-serve \
        color-global-up color-global-down color-global-prepare color-global-native-probe color-global-dynamic-probe color-global-index color-global-evaluate color-global-format color-global-serve \
        infra-start infra-stop infra-reset infra-logs apps-start apps-stop \
        redis-cli redis-flush redis-info \
        nats-setup-streams nats-stream-list nats-stream-info \
        migrate psql psql-ingestor psql-media psql-tags psql-user db-studio-ingestor db-studio-media db-studio-user \
        ingestor-dev ingestor-build ingestor-start ingestor-test ingestor-test-watch ingestor-format ingestor-lint ingestor-check \
        ingestor-docker-build ingestor-docker-run ingestor-docker-stop ingestor-docker-logs \
        ingestor-e2e-test ingestor-e2e-test-watch ingestor-e2e-verify \
        user-dev user-build user-start user-test user-test-watch user-format user-lint user-check \
        user-docker-build user-docker-run user-docker-stop user-docker-logs \
        media-dev media-build media-start media-test media-test-watch media-format media-lint media-check \
        variant-generator-dev variant-generator-build variant-generator-start variant-generator-test variant-generator-test-watch variant-generator-format variant-generator-lint variant-generator-check \
        color-extractor-dev color-extractor-build color-extractor-start color-extractor-test color-extractor-test-watch color-extractor-format color-extractor-lint color-extractor-check \
        color-extractor-docker-build color-extractor-docker-run color-extractor-docker-stop color-extractor-docker-logs \
        tags-dev tags-build tags-start tags-test tags-test-watch tags-format tags-lint tags-check \
        tags-docker-build tags-docker-run tags-docker-stop tags-docker-logs \
        gateway-dev gateway-build gateway-start gateway-test gateway-test-watch gateway-format gateway-lint gateway-check \
        web-dev web-build web-preview web-format web-lint web-check web-test web-test-watch \
        web-e2e-test web-e2e-test-ui web-e2e-test-unit web-e2e-check-types \
        react-muuri-build react-muuri-test react-muuri-test-watch react-muuri-format react-muuri-lint react-muuri-check react-muuri-storybook react-muuri-storybook-build \
        docs-dev docs-build docs-start \
        openapi-generate docs-generate openapi-verify \
        worktree-remove sandcastle-auth sandcastle-test sandcastle-check-types \
        dev build test test-watch test-unit test-integration test-e2e test-ui storage-test storage-infra-test coverage-summary crap check-crap crap-check-types format lint check-types ci ci-force clean help

# ─── Worktree-Aware Variables ────────────────────────────────────────────────
# Load .worktree if it exists (generated by scripts/setup-worktree.mjs via pnpm install).
# Variables from .worktree override the defaults below.
-include .worktree

COMPOSE_PROJECT_NAME ?= wallpaperdb
INGRESS_PORT         ?= 8000
POSTGRES_HOST_PORT   ?= 8001
S3_API_HOST_PORT     ?= 8002
NATS_HOST_PORT       ?= 8003
REDIS_HOST_PORT      ?= 8004
OPENSEARCH_HOST_PORT ?= 8005
OTEL_HTTP_HOST_PORT  ?= 8006
OTEL_GRPC_HOST_PORT  ?= 8007

export COMPOSE_PROJECT_NAME
export INGRESS_PORT
export CRAP_THRESHOLD

# Convenience shorthand for all infra docker compose commands.
# Uses deferred expansion (=) so COMPOSE_PROJECT_NAME is resolved at use time.
INFRA_COMPOSE = docker compose -p $(COMPOSE_PROJECT_NAME) -f infra/docker-compose.yml
APPS_COMPOSE  = docker compose -p $(COMPOSE_PROJECT_NAME) -f infra/docker-compose.apps.yml

SANDCASTLE_AUTH_DIR ?= .sandcastle
SANDCASTLE_OPENCODE_AUTH ?= $(HOME)/.local/share/opencode/auth.json
GITHUB_CLI ?= gh
TURBO := "$(CURDIR)/node_modules/.bin/turbo"

help:
	@echo "WallpaperDB - Available commands:"
	@echo "  make color-proportions - Prepare the interactive color-proportion prototype"
	@echo "  make color-proportions-serve - Prepare and serve the proportion editor"
	@echo "  make color-proportions-prepare / color-proportions-diagnose - Build palette data / check ratio semantics"
	@echo "  make color-proportions-evaluate / color-proportions-audit - Evaluate real images / independently verify transport"
	@echo "  make color-proportions-format - Format only the proportion prototype sources"
	@echo "  make color-ranges / color-ranges-serve - Prepare / serve the per-color range prototype"
	@echo "  make color-ranges-diagnose / color-ranges-evaluate - Verify ranges / compare palettes with source pixels"
	@echo "  make color-ranges-format - Format only the range prototype sources"
	@echo "  make color-global-up / color-global-down - Start/stop isolated global-ranking OpenSearch"
	@echo "  make color-global-prepare / color-global-index - Prepare pixel features / index the global-ranking corpus"
	@echo "  make color-global-evaluate - Verify global order, pagination and query performance"
	@echo "  make color-global-accuracy - Check source sampling convergence at 256 vs 1024 pixels"
	@echo "  make color-global-sampling - Compare resized measurements with original-pixel samples"
	@echo "  make color-global-adaptive / color-global-report - Measure safe range expansion / render evidence"
	@echo "  make color-global-joint-probe / color-global-bounded-probe / color-global-joint-bounded-probe - Check global joint ordering and pagination"
	@echo "  make color-global-multi-index - Build original-pixel joint indexes (GLOBAL_COUNTS='' for just the real corpus)"
	@echo "  make color-global-multi-probe / color-global-multi-evaluate - Check and measure one-to-five-color matching"
	@echo "  make color-global-multi-fast-probe / color-global-multi-fast-evaluate - Verify / measure the optimized scoring script"
	@echo "  make color-global-varied - Compare 60 changing queries and a concurrency-four pass"
	@echo "  make color-global-planner - Verify and benchmark selective-filter query planning"
	@echo "  make color-global-multi-finalize - Verify million-document global winners with extended reference queries"
	@echo "  make color-global-settle / color-global-resources - Measure settled index sizes / sustained resource use"
	@echo "  make color-global-native-probe / color-global-dynamic-probe - Verify prototype OpenSearch queries"
	@echo "  make color-global-format / color-global-serve - Format / serve the global-ranking prototype"
	@echo "  make color-benchmark - Run the isolated 100-wallpaper color search experiment"
	@echo "  make color-benchmark-diagnose - Run color ranking diagnostic cases"
	@echo "  make color-benchmark-corpus - Download the pinned experiment wallpapers"
	@echo "  make color-benchmark-up / color-benchmark-down - Start/stop scratch search and NATS"
	@echo "  make color-benchmark-extract - Run production extraction/event projection on the corpus"
	@echo "  make color-benchmark-rank - Compare algorithms on the already extracted corpus"
	@echo "  make color-benchmark-blind-review - Generate blinded visual comparison sheets"
	@echo "  make color-benchmark-analysis - Check candidate retrieval and query variation"
	@echo "  make color-benchmark-format - Format the experiment source files"
	@echo "  make color-benchmark-report / color-benchmark-serve - Build/view the comparison report"
	@echo "  make color-review-serve - Serve the batch human color review on port 8222"
	@echo "  make color-review-test - Verify review submissions and durable storage"
	@echo "  make color-eval-test - Verify color evaluation datasets, metrics, adapters and run reports"
	@echo "  make color-eval-run - Evaluate configured methods (COLOR_EVAL_CONFIG=... optional)"
	@echo "  make color-eval-report - Rebuild a saved run report (COLOR_EVAL_RUN=..., COLOR_EVAL_PREVIOUS=... optional)"
	@echo "  make color-eval-format - Format the evaluation loop source"
	@echo "  make color-eval-serve - View saved color evaluation runs on port 8224"
	@echo "  make color-exploration-corpus / color-exploration-index - Import all wallpapers / create the real prototype index"
	@echo "  make color-exploration-evaluate / color-exploration-summary - Run feedback comparisons / render consolidated findings"
	@echo "  make color-exploration-browser - Try all prototypes on port 8225"
	@echo "  make color-histogram-inspector - Inspect histogram bins and score effects on port 8226"
	@echo "  make color-overlap-index / -test / -scale - Explore 1024 overlapping coverage/quality regions"
	@echo "  make color-overlap-bucket-index - Build or verify the 16/64/256 bucket comparison indexes"
	@echo "  make color-cutoff-index / -resume / -test / -integration / -smoke / -scale - Compare pixel cutoffs and feathering"
	@echo "  make color-shade-prepare / -test / -integration / -evaluate / -neutral-audit - Compare shade-aware color tolerance"
	@echo "  make color-shade-pair-replay / -probe - Diagnose red versus orange ranking feedback"
	@echo "  make color-hue-prepare / -test / -integration / -evaluate / -audit - Compare stricter hue with shade tolerance"
	@echo "  make color-cutoff-heavy - Test concurrent unfiltered five-color queries on the million-record projection"
	@echo "  make color-quality-curve-test / -scale - Check smooth power quality scoring and its projected scale cost"
	@echo "  make color-favorite-corpus-test / color-favorite-scale-test / color-favorite-scale - Benchmark the preserved strict-hue favorite"
	@echo "  make color-favorite-resources - Observe isolated benchmark CPU and memory counters"
	@echo "  make color-favorite-arrival-test / color-favorite-arrival - Check independent query arrivals for the favorite"
	@echo "  make color-favorite-maintained-test / color-favorite-maintained - Recheck favorite queries after index maintenance"
	@echo "  make color-favorite-maintenance-test / color-favorite-maintenance - Record settled benchmark index layouts"
	@echo "  make color-favorite-completion-test / color-favorite-completion - Complete the retained full-schema query pilot"
	@echo "  make color-favorite-compiled-encoder-test / color-favorite-compiled-encoder-benchmark - Verify and time cached utility indexing plans"
	@echo "  make color-favorite-compiled-index-test / color-favorite-compiled-index - Build isolated utility indexes with the cached encoder"
	@echo "  make color-favorite-optimization-arrival-audit-test / color-favorite-optimization-arrival-audit - Independently audit saved query-arrival evidence"
	@echo "  make color-favorite-performance-test - Check immutable performance page artifacts"
	@echo "  make color-favorite-transport-diagnostic-test / -diagnostic - Trace bounded-query transport without scoring changes"
	@echo "  make color-favorite-pooled-test / -pooled-fidelity-test / -pooled-fidelity - Check pooled PIT cleanup with unchanged scoring"
	@echo "  make color-favorite-pooled-adapter-test - Check pooled feedback integration"
	@echo "  make color-favorite-multishard-fidelity-test / -fidelity - Check projected utilities on three primary shards"
	@echo "  make color-favorite-multiplicity-test / -fidelity-test / -fidelity - Verify repeated target weights in a separate prototype"
	@echo "  make color-favorite-maxima-fidelity-test / color-favorite-maxima-fidelity - Verify global maxima pruning against numeric service rankings"
	@echo "  make color-favorite-docvalue-fetch-test / -fidelity / color-favorite-docvalue-adapter-test - Check result retrieval without stored-field reads"
	@echo "  make color-favorite-bulk-scheduler-test - Verify bounded parallel indexing and failure receipts"
	@echo "  make color-favorite-preset-workload-test - Verify balanced queries across all nine score presets"
	@echo "  make color-linked-strictness-test / -index - Prepare compact three/five-step color preference prototypes"
	@echo "  make color-linked-strictness-lab-test - Check original/linked preference API behavior"
	@echo "  make color-linked-strictness-verify - Verify compact rankings against original and precomputed service results"
	@echo "  make color-linked-strictness-feedback-test - Check linked-slider feedback-loop adapter"
	@echo "  make color-favorite-sorted-test - Verify native numeric-sort favorite prototypes"
	@echo "  make color-dark-red-identify / -diagnose - Reproduce dark-red rankings and inspect color-distance losses"
	@echo "  make color-overlap-fidelity - Measure nearest-anchor approximation on original pixels"
	@echo "  make color-overlap-diversity - Probe many distinct query regions on the million-record index"
	@echo "  make color-overlap-inspector / -smoke - Inspect overlapping regions on port 8227"
	@echo "  make color-histogram-inspector-test / -integration - Verify inspector contracts / real score explanations"
	@echo "  make color-histogram-inspector-smoke - Compare both live pages and save diagnostic receipts"
	@echo "  make color-histogram-inspector-browser-check - Inspect the new UI with an isolated browser session"
	@echo "  make color-exploration-scale / color-exploration-rank-scale - Run isolated scale and concurrency profiles"
	@echo "  make color-exploration-arrival-load - Measure scheduled query arrivals and queue delay"
	@echo "  make color-exploration-clickhouse-up / -index / -test / -scale - Compare exact palette scoring in ClickHouse"
	@echo "  make color-exploration-precision-grid-index / -test / -scale - Explore native indexed picked-color utilities"
	@echo "  make color-exploration-native-probe - Verify native quality/area scoring against real OpenSearch"
	@echo "  make color-exploration-query-test - Verify structured and textual color intent consistency"
	@echo "  make color-exploration-palette-mass-assessment - Reproduce the rejected quality-mass pruning diagnostic"
	@echo "  make color-exploration-precision-precomputed-index - Index precomputed perceptual palette coordinates"
	@echo "  make color-exploration-precision-precomputed-probe - Compare precomputed palette scores and latency"
	@echo "  make color-exploration-recall - Compare native ANN retrieval with exact OpenSearch references"
	@echo "  make color-exploration-palette-bounds / color-exploration-palette-cell-index - Prepare safe precision bounds"
	@echo "  make color-exploration-refinement-features / color-exploration-refinement-index - Prepare relative highlight fields"
	@echo "  make color-exploration-rank-index - Create the indexed utility prototype index"
	@echo "  make color-exploration-browser-smoke / color-exploration-browser-check - Verify live UI APIs / browser automation"
	@echo "  make color-exploration-relative-probe - Verify relative highlight service scores"
	@echo "  make color-exploration-test - Verify prototype query and corpus contracts"
	@echo "  make color-exploration-test-integration - Include every real OpenSearch prototype check"
	@echo "  make color-exploration-scale-up - Start isolated OpenSearch 2.11 scale node (port19217, 8 CPU, 12 GiB)"
	@echo "  make color-exploration-scale-stop - Stop the isolated scale node and retain its indexes"
	@echo ""
	@echo "Current worktree: project=$(COMPOSE_PROJECT_NAME), ingress=http://localhost:$(INGRESS_PORT)"
	@echo ""
	@echo "Infrastructure:"
	@echo "  make infra-start    - Start all infrastructure services"
	@echo "  make infra-stop     - Stop all infrastructure services"
	@echo "  make infra-reset    - Reset all infrastructure data (WARNING: deletes all data)"
	@echo "  make infra-logs     - Tail logs from all infrastructure services"
	@echo "  make apps-start     - Start all application services"
	@echo "  make apps-stop      - Stop all application services"
	@echo ""
	@echo "Redis:"
	@echo "  make redis-cli      - Connect to Redis CLI"
	@echo "  make redis-flush    - Flush all Redis data (WARNING: deletes all data)"
	@echo "  make redis-info     - Show Redis server info"
	@echo ""
	@echo "NATS:"
	@echo "  make nats-setup-streams - Setup all required NATS JetStream streams"
	@echo "  make nats-stream-list   - List all NATS streams"
	@echo "  make nats-stream-info   - Show info for WALLPAPER stream"
	@echo ""
	@echo "Database:"
	@echo "  make migrate            - Run database migrations (apply to local infra)"
	@echo "  make psql               - Open psql shell (default database)"
	@echo "  make psql-ingestor      - Open psql shell (wallpaperdb_ingestor database)"
	@echo "  make psql-media         - Open psql shell (wallpaperdb_media database)"
	@echo "  make psql-tags          - Open psql shell (wallpaperdb_tags database)"
	@echo "  make psql-user          - Open psql shell (wallpaperdb_user database)"
	@echo "  make db-studio-ingestor - Start Drizzle Studio for ingestor"
	@echo "  make db-studio-media    - Start Drizzle Studio for media"
	@echo "  make db-studio-user     - Start Drizzle Studio for user"
	@echo ""
	@echo "Ingestor Service:"
	@echo "  make ingestor-dev        - Start ingestor in development mode"
	@echo "  make ingestor-build      - Build ingestor for production"
	@echo "  make ingestor-start      - Start ingestor in production mode"
	@echo "  make ingestor-test       - Run ingestor tests"
	@echo "  make ingestor-test-watch - Run ingestor tests in watch mode"
	@echo "  make ingestor-format     - Format ingestor code"
	@echo "  make ingestor-lint       - Lint ingestor code"
	@echo ""
	@echo "User Service:"
	@echo "  make user-dev        - Start user service in development mode"
	@echo "  make user-build      - Build user service for production"
	@echo "  make user-start      - Start user service in production mode"
	@echo "  make user-test       - Run user service tests"
	@echo "  make user-test-watch - Run user service tests in watch mode"
	@echo "  make user-format     - Format user service code"
	@echo "  make user-lint       - Lint user service code"
	@echo ""
	@echo "Media Service:"
	@echo "  make media-dev        - Start media service in development mode"
	@echo "  make media-build      - Build media service for production"
	@echo "  make media-start      - Start media service in production mode"
	@echo "  make media-test       - Run media service tests"
	@echo "  make media-test-watch - Run media service tests in watch mode"
	@echo "  make media-format     - Format media service code"
	@echo "  make media-lint       - Lint media service code"
	@echo ""
	@echo "Variant Generator Service:"
	@echo "  make variant-generator-dev        - Start variant-generator in development mode"
	@echo "  make variant-generator-build      - Build variant-generator for production"
	@echo "  make variant-generator-start      - Start variant-generator in production mode"
	@echo "  make variant-generator-test       - Run variant-generator tests"
	@echo "  make variant-generator-test-watch - Run variant-generator tests in watch mode"
	@echo "  make variant-generator-format     - Format variant-generator code"
	@echo "  make variant-generator-lint       - Lint variant-generator code"
	@echo ""
	@echo "Color Extractor Service:"
	@echo "  make color-extractor-dev        - Start color-extractor in development mode"
	@echo "  make color-extractor-build      - Build color-extractor for production"
	@echo "  make color-extractor-start      - Start color-extractor in production mode"
	@echo "  make color-extractor-test       - Run color-extractor tests"
	@echo "  make color-extractor-test-watch - Run color-extractor tests in watch mode"
	@echo "  make color-extractor-format     - Format color-extractor code"
	@echo "  make color-extractor-lint       - Lint color-extractor code"
	@echo ""
	@echo "Tags Service:"
	@echo "  make tags-dev        - Start tags service in development mode"
	@echo "  make tags-build      - Build tags service for production"
	@echo "  make tags-start      - Start tags service in production mode"
	@echo "  make tags-test       - Run tags service tests"
	@echo "  make tags-test-watch - Run tags service tests in watch mode"
	@echo "  make tags-format     - Format tags service code"
	@echo "  make tags-lint       - Lint tags service code"
	@echo ""
	@echo "Gateway Service:"
	@echo "  make gateway-dev        - Start gateway service in development mode"
	@echo "  make gateway-build      - Build gateway service for production"
	@echo "  make gateway-start      - Start gateway service in production mode"
	@echo "  make gateway-test       - Run gateway service tests"
	@echo "  make gateway-test-watch - Run gateway service tests in watch mode"
	@echo "  make gateway-format     - Format gateway service code"
	@echo "  make gateway-lint       - Lint gateway service code"
	@echo ""
	@echo "Web Frontend:"
	@echo "  make web-dev        - Start web frontend in development mode"
	@echo "  make web-build      - Build web frontend for production"
	@echo "  make web-preview    - Preview production build"
	@echo "  make web-test       - Run web frontend tests"
	@echo "  make web-test-watch - Run web frontend tests in watch mode"
	@echo "  make web-format     - Format web frontend code"
	@echo "  make web-lint       - Lint web frontend code"
	@echo "  make web-check      - Type check web frontend"
	@echo ""
	@echo "Browser E2E Workspace:"
	@echo "  make web-e2e-test        - Run browser E2E tests"
	@echo "  make web-e2e-test-ui     - Run browser E2E tests in Playwright UI mode"
	@echo "  make web-e2e-test-unit   - Run browser E2E workspace unit tests"
	@echo "  make web-e2e-check-types - Type check browser E2E workspace"
	@echo ""
	@echo "React Muuri Package:"
	@echo "  make react-muuri-build          - Build react-muuri package"
	@echo "  make react-muuri-test           - Run react-muuri tests"
	@echo "  make react-muuri-test-watch     - Run react-muuri tests in watch mode"
	@echo "  make react-muuri-format         - Format react-muuri code"
	@echo "  make react-muuri-lint           - Lint react-muuri code"
	@echo "  make react-muuri-check          - Type check react-muuri"
	@echo "  make react-muuri-storybook      - Start Storybook dev server (http://localhost:6006)"
	@echo "  make react-muuri-storybook-build - Build Storybook for production"
	@echo ""
	@echo "Ingestor Docker:"
	@echo "  make ingestor-docker-build - Build ingestor Docker image"
	@echo "  make ingestor-docker-run   - Run ingestor Docker container (uses infra/.env)"
	@echo "  make ingestor-docker-stop  - Stop ingestor Docker container"
	@echo "  make ingestor-docker-logs  - View ingestor Docker container logs"
	@echo ""
	@echo "User Docker:"
	@echo "  make user-docker-build - Build user Docker image"
	@echo "  make user-docker-run   - Run user Docker container (uses infra/.env)"
	@echo "  make user-docker-stop  - Stop user Docker container"
	@echo "  make user-docker-logs  - View user Docker container logs"
	@echo ""
	@echo "Tags Docker:"
	@echo "  make tags-docker-build - Build tags Docker image"
	@echo "  make tags-docker-run   - Run tags Docker container (uses infra/.env)"
	@echo "  make tags-docker-stop  - Stop tags Docker container"
	@echo "  make tags-docker-logs  - View tags Docker container logs"
	@echo ""
	@echo "Ingestor E2E Tests:"
	@echo "  make ingestor-e2e-test       - Run E2E tests against Docker container"
	@echo "  make ingestor-e2e-test-watch - Run E2E tests in watch mode"
	@echo "  make ingestor-e2e-verify     - Verify no app code imports in E2E tests"
	@echo ""
	@echo "Color Extractor Docker:"
	@echo "  make color-extractor-docker-build - Build color-extractor Docker image"
	@echo "  make color-extractor-docker-run   - Run color-extractor Docker container (uses infra/.env)"
	@echo "  make color-extractor-docker-stop  - Stop color-extractor Docker container"
	@echo "  make color-extractor-docker-logs  - View color-extractor Docker container logs"
	@echo ""
	@echo "Documentation:"
	@echo "  make docs-dev       - Start documentation dev server (http://localhost:3002)"
	@echo "  make docs-build     - Build documentation for production"
	@echo "  make docs-start     - Start documentation production server"
	@echo ""
	@echo "OpenAPI:"
	@echo "  make openapi-generate - Generate OpenAPI specs (swagger.json) for all services"
	@echo "  make docs-generate    - Generate API documentation from OpenAPI specs"
	@echo "  make openapi-verify   - Verify OpenAPI specs can be generated"
	@echo ""
	@echo "Worktree:"
	@echo "  make worktree-remove - Tear down this worktree's containers and release its slot"
	@echo "  make sandcastle-auth - Refresh local Sandcastle credentials"
	@echo "  make sandcastle-test - Run Sandcastle runner unit tests"
	@echo "  make sandcastle-check-types - Type check the Sandcastle runner"
	@echo ""
	@echo "All Services:"
	@echo "  make dev        - Start all services in development mode"
	@echo "  make build      - Build all services"
	@echo "  make test       - Run all tests"
	@echo "  make test-watch - Run all tests in watch mode"
	@echo "  make format     - Format all code"
	@echo "  make lint       - Lint all code"
	@echo ""
	@echo "Testing (by intensity):"
	@echo "  make test-unit         - Run unit tests (fast, no containers)"
	@echo "  make test-integration  - Run integration tests (uses Testcontainers)"
	@echo "  make test-e2e          - Run E2E tests (heavy container usage, sequential)"
	@echo "  make test-ui           - Run tests with Vitest UI"
	@echo "  make storage-test      - Test S3 compatibility against SeaweedFS"
	@echo "  make storage-infra-test - Test Compose storage auth, bootstrap, and persistence"
	@echo "  make coverage-summary  - Display AI-friendly coverage summary"
	@echo "  make crap              - Rank all source functions by CRAP using current unit/integration coverage"
	@echo "  make check-crap CRAP_THRESHOLD=<n> - Check an explicit CRAP threshold locally"
	@echo ""
	@echo "CI/Local Parity:"
	@echo "  make ci                - Run full CI pipeline locally"
	@echo "  make ci-force          - Run full CI pipeline (skip turbo cache)"
	@echo "  make check-types       - Run type checking on all packages and CRAP tooling"
	@echo "  make crap-check-types  - Type check the CRAP script and configuration"
	@echo ""
	@echo "Cleanup:"
	@echo "  make clean             - Remove all generated artifacts (node_modules, caches, build output)"
	@echo ""

infra-start:
	@$(INFRA_COMPOSE) up -d
	@echo ""
	@echo "Infrastructure started. Project: $(COMPOSE_PROJECT_NAME)"
	@echo ""
	@echo "Service endpoints:"
	@echo "  Postgres:    localhost:$(POSTGRES_HOST_PORT)"
	@echo "  SeaweedFS S3: http://localhost:$(S3_API_HOST_PORT)"
	@echo "  NATS:        nats://localhost:$(NATS_HOST_PORT)"
	@echo "  Redis:       localhost:$(REDIS_HOST_PORT)"
	@echo "  OpenSearch:  http://localhost:$(OPENSEARCH_HOST_PORT)"
	@echo "  OTEL HTTP:   http://localhost:$(OTEL_HTTP_HOST_PORT)"
	@echo "  OTEL gRPC:   localhost:$(OTEL_GRPC_HOST_PORT)"
	@echo ""
	@echo "Admin UIs available via Caddy ingress at http://localhost:$(INGRESS_PORT)"
	@echo "  Grafana:             /grafana"
	@echo "  pgAdmin:              /pgadmin"
	@echo "  OpenSearch Dashboards: /opensearch-dashboards"
	@echo "  NATS Monitoring:     /nats"

infra-stop:
	@$(INFRA_COMPOSE) down

infra-reset:
	@echo "WARNING: This will delete all data for project $(COMPOSE_PROJECT_NAME)!"
	@read -p "Are you sure? (yes/no): " REPLY && \
		[ "$$REPLY" = "yes" ] || { echo "Reset cancelled."; exit 1; }
	@$(INFRA_COMPOSE) down -v
	@echo "Infrastructure reset complete!"

infra-logs:
	@$(INFRA_COMPOSE) logs -f

apps-start:
	@$(APPS_COMPOSE) up -d --build

apps-stop:
	@$(APPS_COMPOSE) down

# Redis commands
redis-cli:
	@$(INFRA_COMPOSE) exec redis redis-cli

redis-flush:
	@$(INFRA_COMPOSE) exec redis redis-cli FLUSHALL

redis-info:
	@$(INFRA_COMPOSE) exec redis redis-cli INFO

# NATS commands
nats-setup-streams:
	@NATS_SERVER=nats://localhost:$(NATS_HOST_PORT) ./infra/nats/init/setup-streams.sh

nats-stream-list:
	@nats stream list --server nats://localhost:$(NATS_HOST_PORT)

nats-stream-info:
	@nats stream info WALLPAPER --server nats://localhost:$(NATS_HOST_PORT)

# Database commands
migrate:
	@echo "Running database migrations..."
	@$(TURBO) run db:migrate
	@echo "✓ Database migrations completed"

psql:
	@$(INFRA_COMPOSE) exec postgres psql -U wallpaperdb

psql-ingestor:
	@$(INFRA_COMPOSE) exec postgres psql -U wallpaperdb -d wallpaperdb_ingestor

psql-media:
	@$(INFRA_COMPOSE) exec postgres psql -U wallpaperdb -d wallpaperdb_media

psql-tags:
	@$(INFRA_COMPOSE) exec postgres psql -U wallpaperdb -d wallpaperdb_tags

psql-user:
	@$(INFRA_COMPOSE) exec postgres psql -U wallpaperdb -d wallpaperdb_user

db-studio-ingestor:
	@pnpm --filter @wallpaperdb/ingestor db:studio

db-studio-media:
	@pnpm --filter @wallpaperdb/media db:studio

db-studio-user:
	@pnpm --filter @wallpaperdb/user db:studio

# Ingestor service commands
ingestor-dev:
	@$(TURBO) run dev --filter=@wallpaperdb/ingestor

ingestor-build:
	@$(TURBO) run build --filter=@wallpaperdb/ingestor

ingestor-start:
	@$(TURBO) run start --filter=@wallpaperdb/ingestor

ingestor-test:
	@$(TURBO) run test --filter=@wallpaperdb/ingestor

ingestor-test-watch:
	@$(TURBO) run test:watch --filter=@wallpaperdb/ingestor

ingestor-format:
	@$(TURBO) run format --filter=@wallpaperdb/ingestor

ingestor-lint:
	@$(TURBO) run lint --filter=@wallpaperdb/ingestor

ingestor-check:
	@$(TURBO) run check --filter=@wallpaperdb/ingestor

# User service commands
user-dev:
	@$(TURBO) run dev --filter=@wallpaperdb/user

user-build:
	@$(TURBO) run build --filter=@wallpaperdb/user

user-start:
	@$(TURBO) run start --filter=@wallpaperdb/user

user-test:
	@$(TURBO) run test --filter=@wallpaperdb/user

user-test-watch:
	@$(TURBO) run test:watch --filter=@wallpaperdb/user

user-format:
	@$(TURBO) run format --filter=@wallpaperdb/user

user-lint:
	@$(TURBO) run lint --filter=@wallpaperdb/user

user-check:
	@$(TURBO) run check --filter=@wallpaperdb/user

# Tags service commands
tags-dev:
	@$(TURBO) run dev --filter=@wallpaperdb/tags

tags-build:
	@$(TURBO) run build --filter=@wallpaperdb/tags

tags-start:
	@$(TURBO) run start --filter=@wallpaperdb/tags

tags-test:
	@$(TURBO) run test --filter=@wallpaperdb/tags

tags-test-watch:
	@$(TURBO) run test:watch --filter=@wallpaperdb/tags

tags-format:
	@$(TURBO) run format --filter=@wallpaperdb/tags

tags-lint:
	@$(TURBO) run lint --filter=@wallpaperdb/tags

tags-check:
	@$(TURBO) run check --filter=@wallpaperdb/tags

# Media service commands
media-dev:
	@$(TURBO) run dev --filter=@wallpaperdb/media

media-build:
	@$(TURBO) run build --filter=@wallpaperdb/media

media-start:
	@$(TURBO) run start --filter=@wallpaperdb/media

media-test:
	@$(TURBO) run test --filter=@wallpaperdb/media

media-test-watch:
	@$(TURBO) run test:watch --filter=@wallpaperdb/media

media-format:
	@$(TURBO) run format --filter=@wallpaperdb/media

media-lint:
	@$(TURBO) run lint --filter=@wallpaperdb/media

media-check:
	@$(TURBO) run check --filter=@wallpaperdb/media

# Variant Generator service commands
variant-generator-dev:
	@$(TURBO) run dev --filter=@wallpaperdb/variant-generator

variant-generator-build:
	@$(TURBO) run build --filter=@wallpaperdb/variant-generator

variant-generator-start:
	@$(TURBO) run start --filter=@wallpaperdb/variant-generator

variant-generator-test:
	@$(TURBO) run test --filter=@wallpaperdb/variant-generator

variant-generator-test-watch:
	@$(TURBO) run test:watch --filter=@wallpaperdb/variant-generator

variant-generator-format:
	@$(TURBO) run format --filter=@wallpaperdb/variant-generator

variant-generator-lint:
	@$(TURBO) run lint --filter=@wallpaperdb/variant-generator

variant-generator-check:
	@$(TURBO) run check --filter=@wallpaperdb/variant-generator

# Color Extractor service commands
color-extractor-dev:
	@$(TURBO) run dev --filter=@wallpaperdb/color-extractor

color-extractor-build:
	@$(TURBO) run build --filter=@wallpaperdb/color-extractor

color-extractor-start:
	@$(TURBO) run start --filter=@wallpaperdb/color-extractor

color-extractor-test:
	@$(TURBO) run test --filter=@wallpaperdb/color-extractor

color-extractor-test-watch:
	@$(TURBO) run test:watch --filter=@wallpaperdb/color-extractor

color-extractor-format:
	@$(TURBO) run format --filter=@wallpaperdb/color-extractor

color-extractor-lint:
	@$(TURBO) run lint --filter=@wallpaperdb/color-extractor

color-extractor-check:
	@$(TURBO) run check --filter=@wallpaperdb/color-extractor

# Color Extractor Docker commands
color-extractor-docker-build:
	@echo "Building color-extractor Docker image..."
	@docker build -t $(COMPOSE_PROJECT_NAME)-color-extractor:latest -f apps/color-extractor/Dockerfile .
	@echo "✓ Docker image built: $(COMPOSE_PROJECT_NAME)-color-extractor:latest"

color-extractor-docker-run:
	@echo "Starting color-extractor Docker container..."
	@if [ ! -f infra/.env ]; then \
		echo "Error: infra/.env file not found. Run 'make infra-start' first."; \
		exit 1; \
	fi
	@. ./infra/.env && docker run --rm -d \
		-p 3007:3007 \
		-e NODE_ENV=production \
		-e PORT=3007 \
		-e S3_ENDPOINT=http://host.docker.internal:$(S3_API_HOST_PORT) \
		-e S3_ACCESS_KEY_ID=$${S3_ACCESS_KEY_ID:-storageadmin} \
		-e S3_SECRET_ACCESS_KEY=$${S3_SECRET_ACCESS_KEY:-storageadmin} \
		-e S3_BUCKET=wallpapers \
		-e NATS_URL=nats://host.docker.internal:$(NATS_HOST_PORT) \
		-e OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:$(OTEL_HTTP_HOST_PORT) \
		--name $(COMPOSE_PROJECT_NAME)-color-extractor \
		$(COMPOSE_PROJECT_NAME)-color-extractor:latest
	@echo "✓ Color Extractor container started"
	@echo "  Health: http://localhost:$(INGRESS_PORT)/color-extractor/health"
	@echo "  Ready:  http://localhost:$(INGRESS_PORT)/color-extractor/ready"

color-extractor-docker-stop:
	@echo "Stopping color-extractor Docker container..."
	@docker stop $(COMPOSE_PROJECT_NAME)-color-extractor 2>/dev/null || echo "Container not running"
	@echo "✓ Color Extractor container stopped"

color-extractor-docker-logs:
	@docker logs -f $(COMPOSE_PROJECT_NAME)-color-extractor

# Gateway service commands
gateway-dev:
	@$(TURBO) run dev --filter=@wallpaperdb/gateway

gateway-build:
	@$(TURBO) run build --filter=@wallpaperdb/gateway

gateway-start:
	@$(TURBO) run start --filter=@wallpaperdb/gateway

gateway-test:
	@$(TURBO) run test --filter=@wallpaperdb/gateway

gateway-test-watch:
	@$(TURBO) run test:watch --filter=@wallpaperdb/gateway

gateway-format:
	@$(TURBO) run format --filter=@wallpaperdb/gateway

gateway-lint:
	@$(TURBO) run lint --filter=@wallpaperdb/gateway

gateway-check:
	@$(TURBO) run check --filter=@wallpaperdb/gateway

# Web frontend commands
web-dev:
	@$(TURBO) run dev --filter=@wallpaperdb/web

web-build:
	@$(TURBO) run build --filter=@wallpaperdb/web

web-preview:
	@$(TURBO) run preview --filter=@wallpaperdb/web

web-format:
	@$(TURBO) run format --filter=@wallpaperdb/web

web-lint:
	@$(TURBO) run lint --filter=@wallpaperdb/web

web-check:
	@$(TURBO) run check-types --filter=@wallpaperdb/web

web-test:
	@$(TURBO) run test --filter=@wallpaperdb/web

web-test-watch:
	@pnpm --filter @wallpaperdb/web test:watch

# React Muuri package commands
react-muuri-build:
	@$(TURBO) run build --filter=@wallpaperdb/react-muuri

react-muuri-test:
	@$(TURBO) run test --filter=@wallpaperdb/react-muuri

react-muuri-test-watch:
	@pnpm --filter @wallpaperdb/react-muuri test:watch

react-muuri-format:
	@$(TURBO) run format --filter=@wallpaperdb/react-muuri

react-muuri-lint:
	@$(TURBO) run lint --filter=@wallpaperdb/react-muuri

react-muuri-check:
	@$(TURBO) run check-types --filter=@wallpaperdb/react-muuri

react-muuri-storybook:
	@pnpm --filter @wallpaperdb/react-muuri storybook

react-muuri-storybook-build:
	@pnpm --filter @wallpaperdb/react-muuri build-storybook

# Ingestor Docker commands
ingestor-docker-build:
	@echo "Building ingestor Docker image..."
	@docker build -t $(COMPOSE_PROJECT_NAME)-ingestor:latest -f apps/ingestor/Dockerfile .
	@echo "✓ Docker image built: $(COMPOSE_PROJECT_NAME)-ingestor:latest"

ingestor-docker-run:
	@echo "Starting ingestor Docker container..."
	@if [ ! -f infra/.env ]; then \
		echo "Error: infra/.env file not found. Run 'make infra-start' first."; \
		exit 1; \
	fi
	@. ./infra/.env && docker run --rm -d \
		-p 3001:3001 \
		-e NODE_ENV=production \
		-e PORT=3001 \
		-e DATABASE_URL=postgresql://$$POSTGRES_USER:$$POSTGRES_PASSWORD@host.docker.internal:$(POSTGRES_HOST_PORT)/$$POSTGRES_DB \
		-e S3_ENDPOINT=http://host.docker.internal:$(S3_API_HOST_PORT) \
		-e S3_ACCESS_KEY_ID=$${S3_ACCESS_KEY_ID:-storageadmin} \
		-e S3_SECRET_ACCESS_KEY=$${S3_SECRET_ACCESS_KEY:-storageadmin} \
		-e S3_BUCKET=wallpapers \
		-e NATS_URL=nats://host.docker.internal:$(NATS_HOST_PORT) \
		-e OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:$(OTEL_HTTP_HOST_PORT) \
		--name $(COMPOSE_PROJECT_NAME)-ingestor \
		$(COMPOSE_PROJECT_NAME)-ingestor:latest
	@echo "✓ Ingestor container started"
	@echo "  Health: http://localhost:$(INGRESS_PORT)/ingestor/health"
	@echo "  Ready:  http://localhost:$(INGRESS_PORT)/ingestor/ready"

ingestor-docker-stop:
	@echo "Stopping ingestor Docker container..."
	@docker stop $(COMPOSE_PROJECT_NAME)-ingestor 2>/dev/null || echo "Container not running"
	@echo "✓ Ingestor container stopped"

ingestor-docker-logs:
	@docker logs -f $(COMPOSE_PROJECT_NAME)-ingestor

# User Docker commands
user-docker-build:
	@echo "Building user Docker image..."
	@docker build -t $(COMPOSE_PROJECT_NAME)-user:latest -f apps/user/Dockerfile .
	@echo "✓ Docker image built: $(COMPOSE_PROJECT_NAME)-user:latest"

user-docker-run:
	@echo "Starting user Docker container..."
	@if [ ! -f infra/.env ]; then \
		echo "Error: infra/.env file not found. Run 'make infra-start' first."; \
		exit 1; \
	fi
	@. ./infra/.env && docker run --rm -d \
		-p 3009:3009 \
		-e NODE_ENV=production \
		-e PORT=3009 \
		-e DATABASE_URL=postgresql://$$POSTGRES_USER:$$POSTGRES_PASSWORD@host.docker.internal:$(POSTGRES_HOST_PORT)/$$POSTGRES_DB \
		-e NATS_URL=nats://host.docker.internal:$(NATS_HOST_PORT) \
		-e OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:$(OTEL_HTTP_HOST_PORT) \
		--name $(COMPOSE_PROJECT_NAME)-user \
		$(COMPOSE_PROJECT_NAME)-user:latest
	@echo "✓ User container started"
	@echo "  Health: http://localhost:$(INGRESS_PORT)/user/health"
	@echo "  Ready:  http://localhost:$(INGRESS_PORT)/user/ready"

user-docker-stop:
	@echo "Stopping user Docker container..."
	@docker stop $(COMPOSE_PROJECT_NAME)-user 2>/dev/null || echo "Container not running"
	@echo "✓ User container stopped"

user-docker-logs:
	@docker logs -f $(COMPOSE_PROJECT_NAME)-user

# Tags Docker commands
tags-docker-build:
	@echo "Building tags Docker image..."
	@docker build -t $(COMPOSE_PROJECT_NAME)-tags:latest -f apps/tags/Dockerfile .
	@echo "✓ Docker image built: $(COMPOSE_PROJECT_NAME)-tags:latest"

tags-docker-run:
	@echo "Starting tags Docker container..."
	@if [ ! -f infra/.env ]; then \
		echo "Error: infra/.env file not found. Run 'make infra-start' first."; \
		exit 1; \
	fi
	@. ./infra/.env && docker run --rm -d \
		-p 3008:3008 \
		-e NODE_ENV=production \
		-e PORT=3008 \
		-e DATABASE_URL=postgresql://$$POSTGRES_USER:$$POSTGRES_PASSWORD@host.docker.internal:$(POSTGRES_HOST_PORT)/$$POSTGRES_DB \
		-e NATS_URL=nats://host.docker.internal:$(NATS_HOST_PORT) \
		-e OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:$(OTEL_HTTP_HOST_PORT) \
		--name $(COMPOSE_PROJECT_NAME)-tags \
		$(COMPOSE_PROJECT_NAME)-tags:latest
	@echo "✓ Tags container started"
	@echo "  Health: http://localhost:$(INGRESS_PORT)/tagging/health"
	@echo "  Ready:  http://localhost:$(INGRESS_PORT)/tagging/ready"

tags-docker-stop:
	@echo "Stopping tags Docker container..."
	@docker stop $(COMPOSE_PROJECT_NAME)-tags 2>/dev/null || echo "Container not running"
	@echo "✓ Tags container stopped"

tags-docker-logs:
	@docker logs -f $(COMPOSE_PROJECT_NAME)-tags

# Ingestor E2E test commands
ingestor-e2e-test:
	@echo "Running E2E tests (builds Docker image first)..."
	@$(TURBO) run test --filter=@wallpaperdb/ingestor-e2e

ingestor-e2e-test-watch:
	@$(TURBO) run test:watch --filter=@wallpaperdb/ingestor-e2e

ingestor-e2e-verify:
	@echo "Verifying E2E tests don't import application code..."
	@pnpm --filter @wallpaperdb/ingestor-e2e verify-no-imports
	@echo "✓ Verification passed - E2E tests are properly isolated"

# Documentation commands
docs-dev:
	@echo "Starting documentation dev server..."
	@$(TURBO) run dev --filter=@wallpaperdb/docs

# Browser E2E commands
web-e2e-test:
	@echo "Running browser E2E tests..."
	@$(TURBO) run test:e2e --filter=@wallpaperdb/web-e2e --concurrency=1

web-e2e-test-ui:
	@echo "Running browser E2E tests in Playwright UI mode..."
	@$(TURBO) run test:e2e:ui --filter=@wallpaperdb/web-e2e --concurrency=1

web-e2e-test-unit:
	@echo "Running browser E2E workspace unit tests..."
	@$(TURBO) run test:unit --filter=@wallpaperdb/web-e2e

web-e2e-check-types:
	@echo "Type checking browser E2E workspace..."
	@$(TURBO) run check-types --filter=@wallpaperdb/web-e2e

docs-build:
	@echo "Building documentation..."
	@$(TURBO) run build --filter=@wallpaperdb/docs

docs-start:
	@echo "Starting documentation production server..."
	@$(TURBO) run start --filter=@wallpaperdb/docs

# OpenAPI commands
openapi-generate:
	@echo "Generating OpenAPI specs..."
	@pnpm --filter @wallpaperdb/ingestor gen:swagger
	@echo "✓ OpenAPI spec generated: apps/ingestor/swagger.json"

docs-generate:
	@echo "Generating API documentation from OpenAPI specs..."
	@pnpm --filter @wallpaperdb/docs gen:swagger-pages
	@echo "✓ API documentation generated in apps/docs/content/docs/openapi/"

openapi-verify:
	@echo "Verifying OpenAPI spec generation..."
	@pnpm --filter @wallpaperdb/ingestor gen:swagger
	@if [ -f apps/ingestor/swagger.json ]; then \
		echo "✓ OpenAPI spec generated successfully"; \
	else \
		echo "✗ Failed to generate OpenAPI spec"; \
		exit 1; \
	fi

worktree-remove:
	@node scripts/teardown-worktree.mjs

sandcastle-auth:
	@if ! command -v "$(GITHUB_CLI)" >/dev/null 2>&1; then \
		echo "GitHub CLI not found. Install 'gh' and run 'gh auth login' first."; \
		exit 1; \
	fi
	@if [ ! -f "$(SANDCASTLE_OPENCODE_AUTH)" ]; then \
		echo "OpenCode auth not found at $(SANDCASTLE_OPENCODE_AUTH). Sign in to OpenCode first."; \
		exit 1; \
	fi
	@github_token="$$( "$(GITHUB_CLI)" auth token )" || { \
		echo "Unable to read GitHub credentials. Run 'gh auth login' first."; \
		exit 1; \
	}; \
	if [ -z "$$github_token" ]; then \
		echo "GitHub CLI returned an empty token. Run 'gh auth login' first."; \
		exit 1; \
	fi; \
	umask 077; \
	mkdir -p "$(SANDCASTLE_AUTH_DIR)/.opencode"; \
	printf 'GH_TOKEN=%s\n' "$$github_token" > "$(SANDCASTLE_AUTH_DIR)/.env"; \
	cp "$(SANDCASTLE_OPENCODE_AUTH)" "$(SANDCASTLE_AUTH_DIR)/.opencode/auth.json"; \
	chmod 600 "$(SANDCASTLE_AUTH_DIR)/.env" "$(SANDCASTLE_AUTH_DIR)/.opencode/auth.json"; \
	echo "Sandcastle credentials refreshed in $(SANDCASTLE_AUTH_DIR)."

sandcastle-test:
	@pnpm sandcastle:test

sandcastle-check-types:
	@pnpm sandcastle:check-types

# All services commands
dev:
	@scripts/check-infra.sh || \
	  (echo "Infra is not running. Start it first with: make infra-start" && exit 1)
	@$(APPS_COMPOSE) watch

build:
	@$(TURBO) run build

test:
	@$(TURBO) run test

test-watch:
	@$(TURBO) run test:watch

# Test commands by intensity
test-unit:
	@echo "Running unit tests (fast, no containers)..."
	@$(TURBO) run test:unit

test-integration:
	@echo "Running integration tests (uses Testcontainers)..."
	@$(TURBO) run test:integration --concurrency=1

test-e2e:
	@echo "Running E2E tests (heavy container usage, sequential)..."
	@$(TURBO) run test:e2e --concurrency=1

test-ui:
	@echo "Starting Vitest UI..."
	@pnpm test:ui

storage-test:
	@$(TURBO) run build --filter='@wallpaperdb/test-utils^...'
	@pnpm --filter @wallpaperdb/test-utils test tests/s3.test.ts

storage-infra-test:
	@node --test scripts/lib/env-pipeline.test.mjs
	@node scripts/test-object-storage.mjs

coverage-summary:
	@node scripts/coverage-summary.js

crap-check-types:
	@pnpm crap:check-types

crap:
	@pnpm exec tsx scripts/crap.mts report

check-crap:
	@pnpm exec tsx scripts/crap.mts check

format:
	@$(TURBO) run format --log-order grouped

lint:
	@$(TURBO) run lint --log-order grouped

lint-fix:
	@$(TURBO) run lint:fix --log-order grouped

check: crap-check-types
	@$(TURBO) run build lint check-types --log-order grouped

install:
	pnpm install

# Throwaway color search research. Separate ports, containers, and indexes.
COLOR_BENCH_DIR = experiments/color-search-benchmark
COLOR_BENCH_TS = node_modules/.bin/tsx --tsconfig $(COLOR_BENCH_DIR)/tsconfig.json -r ./apps/gateway/node_modules/reflect-metadata
COLOR_BENCH_COMPOSE = docker compose -p $(COMPOSE_PROJECT_NAME)-color-benchmark -f $(COLOR_BENCH_DIR)/compose.yml
COLOR_FAVORITE_REAL_DATA ?= $(HOME)/.local/share/wallpaperdb/color-evaluation/opensearch-real-data
export COLOR_FAVORITE_REAL_DATA
COLOR_GLOBAL_BASE_COMPOSE = docker compose -p $(COMPOSE_PROJECT_NAME)-color-global -f $(COLOR_BENCH_DIR)/global-compose.yml
# Preserve the migrated real-corpus volume on subsequent ordinary lab starts.
# The marker is written only after every source/copy file and restored index pass.
COLOR_GLOBAL_COMPOSE = $(COLOR_GLOBAL_BASE_COMPOSE) $(if $(wildcard $(COLOR_FAVORITE_REAL_DATA).verified),-f $(COLOR_BENCH_DIR)/exploration/favorite-real-memory.yml,)

color-benchmark-up:
	@$(COLOR_BENCH_COMPOSE) up -d --wait

color-benchmark-down:
	@$(COLOR_BENCH_COMPOSE) down

color-benchmark-corpus:
	@node $(COLOR_BENCH_DIR)/downloader.mjs

color-benchmark-diagnose:
	@$(COLOR_BENCH_TS) $(COLOR_BENCH_DIR)/diagnose.ts

color-benchmark-extract: color-benchmark-up color-benchmark-corpus
	@$(COLOR_BENCH_TS) $(COLOR_BENCH_DIR)/pipeline.ts

color-benchmark: color-benchmark-extract
	@$(MAKE) color-benchmark-diagnose
	@$(MAKE) color-benchmark-rank
	@$(MAKE) color-benchmark-analysis color-benchmark-report color-benchmark-blind-review

color-benchmark-rank:
	@$(COLOR_BENCH_TS) $(COLOR_BENCH_DIR)/benchmark.ts

color-benchmark-report:
	@node $(COLOR_BENCH_DIR)/report.mjs

color-benchmark-blind-review:
	@node $(COLOR_BENCH_DIR)/review-sheets.mjs

color-benchmark-analysis:
	@node $(COLOR_BENCH_DIR)/analyze.mjs

color-benchmark-format:
	@apps/gateway/node_modules/.bin/biome format --write $(COLOR_BENCH_DIR)/*.ts $(COLOR_BENCH_DIR)/*.mjs

color-benchmark-serve:
	@python3 -m http.server 8220 --bind 127.0.0.1 --directory $(COLOR_BENCH_DIR)

color-proportions: color-proportions-prepare color-proportions-diagnose

color-proportions-prepare: color-benchmark-corpus
	@$(COLOR_BENCH_TS) $(COLOR_BENCH_DIR)/proportions-prepare.ts

color-proportions-diagnose:
	@node $(COLOR_BENCH_DIR)/proportions-diagnose.mjs

color-proportions-evaluate: color-proportions-prepare
	@$(COLOR_BENCH_TS) $(COLOR_BENCH_DIR)/proportions-evaluate.ts

color-proportions-audit:
	@node $(COLOR_BENCH_DIR)/proportions-audit.mjs

color-proportions-format:
	@apps/gateway/node_modules/.bin/biome format --write $(COLOR_BENCH_DIR)/proportions*.ts $(COLOR_BENCH_DIR)/proportions*.mjs

color-proportions-serve: color-proportions
	@node $(COLOR_BENCH_DIR)/proportions-serve.mjs

color-ranges: color-proportions-prepare color-ranges-diagnose

color-ranges-diagnose:
	@node $(COLOR_BENCH_DIR)/ranges-diagnose.mjs

color-ranges-evaluate: color-proportions-prepare
	@$(COLOR_BENCH_TS) $(COLOR_BENCH_DIR)/ranges-evaluate.ts

color-ranges-format:
	@apps/gateway/node_modules/.bin/biome format --write $(COLOR_BENCH_DIR)/ranges*.ts $(COLOR_BENCH_DIR)/ranges*.mjs

color-ranges-serve: color-ranges
	@node $(COLOR_BENCH_DIR)/proportions-serve.mjs

color-global-up:
	@$(COLOR_GLOBAL_COMPOSE) up -d --wait

color-global-down:
	@$(COLOR_GLOBAL_COMPOSE) down

color-global-prepare: color-benchmark-corpus
	@$(COLOR_BENCH_TS) $(COLOR_BENCH_DIR)/global-prepare.ts

color-global-native-probe:
	@node $(COLOR_BENCH_DIR)/global-native.mjs --probe

color-global-dynamic-probe:
	@node $(COLOR_BENCH_DIR)/global-dynamic.mjs --probe

.PHONY: color-global-joint-probe
color-global-joint-probe:
	@node $(COLOR_BENCH_DIR)/global-joint.mjs --probe

color-global-index: color-global-up color-global-prepare
	@node $(COLOR_BENCH_DIR)/global-index.mjs

color-global-evaluate:
	@node $(COLOR_BENCH_DIR)/global-evaluate.mjs

.PHONY: color-global-report
color-global-report:
	@node $(COLOR_BENCH_DIR)/global-report.mjs

.PHONY: color-global-adaptive
color-global-adaptive:
	@node $(COLOR_BENCH_DIR)/global-adaptive.mjs

.PHONY: color-global-sampling
color-global-sampling:
	@$(COLOR_BENCH_TS) $(COLOR_BENCH_DIR)/global-sampling.ts

.PHONY: color-global-multi-index
color-global-multi-index: color-global-up color-global-multi-prepare
	@node $(COLOR_BENCH_DIR)/global-multi-index.mjs

.PHONY: color-global-multi-evaluate
color-global-multi-evaluate:
	@node $(COLOR_BENCH_DIR)/global-multi-evaluate.mjs

.PHONY: color-global-resources
color-global-resources:
	@node $(COLOR_BENCH_DIR)/global-resources.mjs

.PHONY: color-global-settle
color-global-settle:
	@node $(COLOR_BENCH_DIR)/global-settle.mjs

.PHONY: color-global-multi-finalize color-global-multi-fast-probe
color-global-multi-finalize:
	@node $(COLOR_BENCH_DIR)/global-multi-finalize.mjs

color-global-multi-fast-probe:
	@node $(COLOR_BENCH_DIR)/global-multi-fast.mjs --probe

.PHONY: color-global-multi-fast-evaluate
color-global-multi-fast-evaluate:
	@node $(COLOR_BENCH_DIR)/global-multi-fast-evaluate.mjs

.PHONY: color-global-varied
color-global-varied:
	@node $(COLOR_BENCH_DIR)/global-varied.mjs

.PHONY: color-global-accuracy
color-global-accuracy:
	@$(COLOR_BENCH_TS) $(COLOR_BENCH_DIR)/global-accuracy.ts

color-global-format:
	@apps/gateway/node_modules/.bin/biome format --write $(COLOR_BENCH_DIR)/global*.ts $(COLOR_BENCH_DIR)/global*.mjs

color-global-serve:
	@node $(COLOR_BENCH_DIR)/global-server.mjs

.PHONY: color-review-serve color-review-test
color-review-serve:
	@node $(COLOR_BENCH_DIR)/evaluation/review-server.mjs

color-review-test:
	@node --test $(COLOR_BENCH_DIR)/evaluation/review-server.test.mjs

COLOR_EVAL_CONFIG ?= $(COLOR_BENCH_DIR)/evaluation/loop/configs/initial.json
.PHONY: color-eval-test color-eval-run color-eval-report color-eval-format color-eval-serve
color-eval-test:
	@node --test $(COLOR_BENCH_DIR)/evaluation/loop/*.test.mjs

color-eval-run:
	@node $(COLOR_BENCH_DIR)/evaluation/loop/cli.mjs run --config "$(COLOR_EVAL_CONFIG)"

color-eval-report:
	@node $(COLOR_BENCH_DIR)/evaluation/loop/cli.mjs report --run "$(COLOR_EVAL_RUN)" $(if $(COLOR_EVAL_PREVIOUS),--previous "$(COLOR_EVAL_PREVIOUS)")

color-eval-format:
	@apps/gateway/node_modules/.bin/biome format --write $(COLOR_BENCH_DIR)/evaluation/loop/*.mjs $(COLOR_BENCH_DIR)/evaluation/loop/configs/*.json

color-eval-serve:
	@node $(COLOR_BENCH_DIR)/evaluation/loop/server.mjs

COLOR_EXP_ARGS ?=
.PHONY: color-exploration-palette-mass-assessment
color-exploration-palette-mass-assessment:
	@node $(COLOR_BENCH_DIR)/exploration/palette-mass-assessment.mjs
.PHONY: color-exploration-query-test
color-exploration-query-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/query-intent.test.mjs
.PHONY: color-exploration-precision-precomputed-index
color-exploration-precision-precomputed-index:
	@node $(COLOR_BENCH_DIR)/exploration/precision-precomputed-index.mjs
.PHONY: color-exploration-precision-precomputed-probe
color-exploration-precision-precomputed-probe:
	@node $(COLOR_BENCH_DIR)/exploration/precision-precomputed-probe.mjs
.PHONY: color-exploration-native-test color-exploration-native-probe
color-exploration-native-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/methods-native-refined.test.mjs
color-exploration-native-probe:
	@node $(COLOR_BENCH_DIR)/exploration/methods-native-refined-probe.mjs
.PHONY: color-exploration-arrival-load
color-exploration-arrival-load:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/arrival-load.mjs $(COLOR_EXP_ARGS)
.PHONY: color-exploration-clickhouse-up color-exploration-clickhouse-index color-exploration-clickhouse-test color-exploration-clickhouse-scale
color-exploration-clickhouse-up:
	@docker compose -p $(COMPOSE_PROJECT_NAME)-color-exploration-clickhouse -f $(COLOR_BENCH_DIR)/exploration/clickhouse-compose.yml up -d
color-exploration-clickhouse-index:
	@node $(COLOR_BENCH_DIR)/exploration/clickhouse-index.mjs $(COLOR_EXP_ARGS)
color-exploration-clickhouse-test:
	@COLOR_EXPLORATION_CLICKHOUSE_TEST=1 node --test $(COLOR_BENCH_DIR)/exploration/methods-clickhouse.test.mjs
color-exploration-clickhouse-scale:
	@node $(COLOR_BENCH_DIR)/exploration/clickhouse-scale.mjs $(COLOR_EXP_ARGS)
.PHONY: color-exploration-precision-grid-index color-exploration-precision-grid-test color-exploration-precision-grid-scale
color-exploration-precision-grid-index:
	@node $(COLOR_BENCH_DIR)/exploration/precision-grid-index.mjs $(COLOR_EXP_ARGS)
color-exploration-precision-grid-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/methods-precision-grid.test.mjs $(COLOR_BENCH_DIR)/exploration/precision-grid-scale.test.mjs
color-exploration-precision-grid-scale:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/precision-grid-scale.mjs $(COLOR_EXP_ARGS)
.PHONY: color-exploration-summary color-exploration-browser-smoke color-exploration-rank-index
color-exploration-summary:
	@node $(COLOR_BENCH_DIR)/exploration/summary.mjs
color-exploration-browser-smoke:
	@node $(COLOR_BENCH_DIR)/exploration/browser-smoke.mjs
color-exploration-rank-index:
	@node $(COLOR_BENCH_DIR)/exploration/rank-features-index.mjs
.PHONY: color-exploration-palette-cell-index
color-exploration-palette-cell-index:
	@node $(COLOR_BENCH_DIR)/exploration/palette-cell-index.mjs
.PHONY: color-exploration-palette-bounds color-exploration-relative-probe
color-exploration-palette-bounds:
	@node $(COLOR_BENCH_DIR)/exploration/methods-palette-bounded.mjs --prepare-bounds
color-exploration-relative-probe:
	@node $(COLOR_BENCH_DIR)/exploration/methods-relative-probe.mjs
.PHONY: color-exploration-recall color-exploration-refinement-index color-exploration-relative-test color-exploration-rank-scale
color-exploration-recall:
	@node $(COLOR_BENCH_DIR)/exploration/recall.mjs
color-exploration-refinement-index:
	@node $(COLOR_BENCH_DIR)/exploration/refinement-index.mjs
color-exploration-relative-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/methods-relative.test.mjs $(COLOR_BENCH_DIR)/exploration/refinement-index.test.mjs
color-exploration-rank-scale:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/rank-features-scale.mjs $(COLOR_EXP_ARGS)
COLOR_BROWSER_COMMAND ?= snapshot -i
.PHONY: color-exploration-refinement-features color-exploration-refinement-feature-test
color-exploration-refinement-features:
	@node $(COLOR_BENCH_DIR)/exploration/refinement-features.mjs
color-exploration-refinement-feature-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/refinement-features.test.mjs
.PHONY: color-exploration-browser-check
color-exploration-browser-check:
	@agent-browser --session color-exploration-browser-t3code-28be15f7 $(COLOR_BROWSER_COMMAND)
.PHONY: color-exploration-scale-up color-exploration-scale-stop
.PHONY: color-exploration-method-test
color-exploration-method-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/methods.test.mjs
color-exploration-scale-up:
	@docker compose -p $(COMPOSE_PROJECT_NAME)-color-exploration-scale -f $(COLOR_BENCH_DIR)/exploration/compose.yml up -d
color-exploration-scale-stop:
	@docker compose -p $(COMPOSE_PROJECT_NAME)-color-exploration-scale -f $(COLOR_BENCH_DIR)/exploration/compose.yml stop opensearch
.PHONY: color-exploration-corpus color-exploration-index color-exploration-evaluate color-exploration-scale color-exploration-browser color-exploration-test color-exploration-corpus-test color-exploration-browser-test
color-exploration-corpus:
	@node $(COLOR_BENCH_DIR)/exploration/corpus.mjs $(COLOR_EXP_ARGS)
color-exploration-index:
	@node $(COLOR_BENCH_DIR)/exploration/cli.mjs index $(COLOR_EXP_ARGS)
color-exploration-evaluate:
	@node $(COLOR_BENCH_DIR)/exploration/cli.mjs evaluate $(COLOR_EXP_ARGS)
color-exploration-scale:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/scale.mjs $(COLOR_EXP_ARGS)
color-exploration-browser:
	@node $(COLOR_BENCH_DIR)/exploration/cli.mjs browser $(COLOR_EXP_ARGS)
color-exploration-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/*.test.mjs
.PHONY: color-exploration-test-integration
color-exploration-test-integration:
	@COLOR_EXPLORATION_METHOD_INTEGRATION=1 \
	 COLOR_EXPLORATION_DIRECT_TEST=1 COLOR_EXPLORATION_INTENT_INTEGRATION=1 \
	 COLOR_EXPLORATION_PRECISION_TYPED_TEST=1 COLOR_EXPLORATION_RANK_FEATURE_INTEGRATION=1 \
	 COLOR_EXPLORATION_PRECISION_PRECOMPUTED_TEST=1 COLOR_EXPLORATION_PRECISION_DUPLICATE_TEST=1 \
	 COLOR_EXPLORATION_PALETTE_BOUNDS_TEST=1 COLOR_EXPLORATION_PALETTE_BOUNDS_INTEGRATION=1 \
	 COLOR_EXPLORATION_FAST_INTEGRATION=1 COLOR_EXPLORATION_ACCENT_INTEGRATION=1 \
	 COLOR_EXPLORATION_CLICKHOUSE_TEST=1 COLOR_HISTOGRAM_INSPECTOR_INTEGRATION=1 COLOR_OVERLAP_INTEGRATION=1 COLOR_CUTOFF_INTEGRATION=1 \
	 node --test $(COLOR_BENCH_DIR)/exploration/*.test.mjs
.PHONY: color-histogram-inspector color-histogram-inspector-test color-histogram-inspector-integration color-histogram-inspector-browser-check color-histogram-inspector-smoke
.PHONY: color-overlap-index color-overlap-test color-overlap-integration color-overlap-scale color-overlap-inspector color-overlap-inspector-test color-overlap-inspector-smoke color-overlap-inspector-browser-check
.PHONY: color-overlap-fidelity
.PHONY: color-overlap-bucket-index
COLOR_CUTOFF_ARGS ?=
.PHONY: color-cutoff-index color-cutoff-resume color-cutoff-test color-cutoff-integration color-cutoff-scale color-cutoff-smoke color-cutoff-heavy
.PHONY: color-quality-curve-test color-quality-curve-scale
.PHONY: color-dark-red-identify color-dark-red-diagnose
COLOR_DARK_RED_ARGS ?=
COLOR_SHADE_ARGS ?=
COLOR_HUE_ARGS ?=
COLOR_FAVORITE_ARGS ?=
.PHONY: color-favorite-optimized-scoring-test color-favorite-utilities-test color-favorite-optimization-test color-favorite-optimization
color-favorite-optimized-scoring-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-optimized-scoring.test.mjs
color-favorite-utilities-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-utilities.test.mjs
color-favorite-optimization-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-optimization-benchmark.test.mjs
color-favorite-optimization:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/favorite-optimization-benchmark.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-favorite-utility-index-test color-favorite-utility-index color-favorite-lab-test color-favorite-lab
color-favorite-utility-index-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-utility-index.test.mjs
color-favorite-utility-index:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-utility-index.mjs $(COLOR_FAVORITE_ARGS)
color-favorite-lab-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-lab.test.mjs
color-favorite-lab:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-lab.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-favorite-optimization-fidelity-test color-favorite-optimization-fidelity
color-favorite-optimization-fidelity-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-optimization-fidelity.test.mjs
color-favorite-optimization-fidelity:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-optimization-fidelity.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-favorite-optimization-audit-test color-favorite-optimization-audit
color-favorite-optimization-audit-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-optimization-audit.test.mjs
color-favorite-optimization-audit:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-optimization-audit.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-favorite-adapter-test color-favorite-typed-scoring-test
color-favorite-adapter-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-adapter.test.mjs
color-favorite-typed-scoring-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-typed-scoring.test.mjs
.PHONY: color-favorite-optimization-pipeline
color-favorite-optimization-pipeline:
	@python3 $(COLOR_BENCH_DIR)/exploration/favorite-optimization-pipeline.py $(COLOR_FAVORITE_ARGS)
COLOR_FAVORITE_BROWSER_ARGS ?= snapshot -i
.PHONY: color-favorite-lab-browser
color-favorite-lab-browser:
	@agent-browser --session favorite-opt-ui-t3code-28be15f7 $(COLOR_FAVORITE_BROWSER_ARGS)
.PHONY: color-favorite-utility-completion-test color-favorite-utility-completion
color-favorite-utility-completion-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-utility-completion.test.mjs
color-favorite-utility-completion:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-utility-completion.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-favorite-precision-test color-favorite-precision-index-test color-favorite-precision-index
color-favorite-precision-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-precision-utilities.test.mjs
color-favorite-precision-index-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-precision-index.test.mjs
color-favorite-precision-index:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-precision-index.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-favorite-precision-fidelity-test color-favorite-precision-fidelity color-favorite-optimization-arrival-test color-favorite-optimization-arrival
color-favorite-precision-fidelity-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-precision-fidelity.test.mjs
color-favorite-precision-fidelity:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-precision-fidelity.mjs $(COLOR_FAVORITE_ARGS)
color-favorite-optimization-arrival-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-optimization-arrival.test.mjs
color-favorite-optimization-arrival:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/favorite-optimization-arrival.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-favorite-optimization-arrival-audit-test color-favorite-optimization-arrival-audit
color-favorite-optimization-arrival-audit-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-optimization-arrival-audit.test.mjs
color-favorite-optimization-arrival-audit:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-optimization-arrival-audit.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-favorite-bounded-utilities-test
color-favorite-bounded-utilities-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-bounded-utilities.test.mjs
.PHONY: color-favorite-execution-fidelity-test color-favorite-execution-fidelity color-favorite-real-preserve color-favorite-real-expanded-up
color-favorite-execution-fidelity-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-execution-fidelity.test.mjs
color-favorite-execution-fidelity:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-execution-fidelity.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-favorite-wide-workload-test color-favorite-optimization-results-test color-favorite-optimization-results
color-favorite-wide-workload-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-wide-workload.test.mjs
color-favorite-optimization-results-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-optimization-results.test.mjs
color-favorite-optimization-results:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-optimization-results.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-favorite-numeric-index-audit-test color-favorite-numeric-index-audit
color-favorite-numeric-index-audit-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-numeric-index-audit.test.mjs
color-favorite-numeric-index-audit:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/favorite-numeric-index-audit.mjs $(COLOR_FAVORITE_ARGS)
COLOR_FAVORITE_REAL_DATA ?= $(HOME)/.local/share/wallpaperdb/color-evaluation/opensearch-real-data
COLOR_FAVORITE_REAL_PRESERVATION ?= $(HOME)/.local/share/wallpaperdb/color-evaluation/exploration/favorite-optimization/2026-09-23/real-node-preservation
color-favorite-real-preserve:
	@python3 $(COLOR_BENCH_DIR)/exploration/favorite-real-node-preserve.py --container $(COMPOSE_PROJECT_NAME)-color-global-opensearch-1 --data-dir $(COLOR_FAVORITE_REAL_DATA) --receipt-dir $(COLOR_FAVORITE_REAL_PRESERVATION)
color-favorite-real-expanded-up:
	@python3 -c 'import json; from pathlib import Path; d=json.loads(Path("$(COLOR_FAVORITE_REAL_PRESERVATION)/preservation.json").read_text()); assert d.get("verified") is True and Path(d["dataDirectory"]).resolve() == Path("$(COLOR_FAVORITE_REAL_DATA)").resolve(), "Data preservation must pass before recreation"'
	@COLOR_FAVORITE_REAL_DATA=$(COLOR_FAVORITE_REAL_DATA) $(COLOR_GLOBAL_BASE_COMPOSE) -f $(COLOR_BENCH_DIR)/exploration/favorite-real-memory.yml up -d --wait
.PHONY: color-favorite-sorted-test
color-favorite-sorted-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-sorted-utilities.test.mjs
.PHONY: color-favorite-docvalue-fetch-test color-favorite-docvalue-fetch-fidelity
color-favorite-docvalue-fetch-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-docvalue-fetch.test.mjs
.PHONY: color-favorite-docvalue-adapter-test
color-favorite-docvalue-adapter-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-docvalue-adapter.test.mjs
color-favorite-docvalue-fetch-fidelity:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-docvalue-fetch-fidelity.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-favorite-bulk-scheduler-test
color-favorite-bulk-scheduler-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-bulk-scheduler.test.mjs

.PHONY: color-favorite-maxima-bounded-test
color-favorite-maxima-bounded-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-maxima-bounded-utilities.test.mjs

.PHONY: color-favorite-maxima-adapter-test
color-favorite-maxima-adapter-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-maxima-adapter.test.mjs
.PHONY: color-favorite-maxima-fidelity-test color-favorite-maxima-fidelity
color-favorite-maxima-fidelity-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-maxima-fidelity.test.mjs
color-favorite-maxima-fidelity:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-maxima-fidelity.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-favorite-corpus-test color-favorite-scale-test color-favorite-scale color-favorite-resources
.PHONY: color-favorite-arrival-test color-favorite-arrival
.PHONY: color-favorite-maintained-test color-favorite-maintained
.PHONY: color-favorite-maintenance-test color-favorite-maintenance
.PHONY: color-favorite-completion-test color-favorite-completion
color-favorite-corpus-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-scale-corpus.test.mjs
color-favorite-scale-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-scale.test.mjs $(COLOR_BENCH_DIR)/exploration/favorite-scale-corpus.test.mjs
color-favorite-scale:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/favorite-scale.mjs $(COLOR_FAVORITE_ARGS)
color-favorite-resources:
	@python3 $(COLOR_BENCH_DIR)/exploration/favorite-resources.py $(COLOR_FAVORITE_ARGS)
color-favorite-arrival-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-arrival.test.mjs
color-favorite-arrival:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/favorite-arrival.mjs $(COLOR_FAVORITE_ARGS)
color-favorite-maintained-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-maintained.test.mjs
color-favorite-maintained:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/favorite-maintained.mjs $(COLOR_FAVORITE_ARGS)
color-favorite-maintenance-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-maintenance.test.mjs
color-favorite-maintenance:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/favorite-maintenance.mjs $(COLOR_FAVORITE_ARGS)
color-favorite-completion-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-completion.test.mjs
color-favorite-completion:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/favorite-completion.mjs $(COLOR_FAVORITE_ARGS)
.PHONY: color-hue-prepare color-hue-test color-hue-integration color-hue-evaluate color-hue-audit
color-hue-prepare:
	@node $(COLOR_BENCH_DIR)/exploration/hue-index.mjs $(COLOR_HUE_ARGS)
color-hue-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/hue-*.test.mjs
color-hue-integration:
	@COLOR_HUE_INTEGRATION=1 node --test $(COLOR_BENCH_DIR)/exploration/hue-*.test.mjs
color-hue-evaluate:
	@node $(COLOR_BENCH_DIR)/exploration/hue-evaluate.mjs $(COLOR_HUE_ARGS)
color-hue-audit:
	@node $(COLOR_BENCH_DIR)/exploration/hue-subset-audit.mjs $(COLOR_HUE_ARGS)
.PHONY: color-shade-prepare color-shade-test color-shade-integration color-shade-evaluate color-shade-neutral-audit
.PHONY: color-shade-pair-replay color-shade-pair-probe
color-shade-pair-replay:
	@node $(COLOR_BENCH_DIR)/exploration/shade-pair-replay.mjs $(COLOR_SHADE_ARGS)
color-shade-pair-probe:
	@node $(COLOR_BENCH_DIR)/exploration/shade-pair-probe.mjs $(COLOR_SHADE_ARGS)
color-shade-prepare:
	@node $(COLOR_BENCH_DIR)/exploration/shade-index.mjs $(COLOR_SHADE_ARGS)
color-shade-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/shade-*.test.mjs
color-shade-integration:
	@COLOR_SHADE_INTEGRATION=1 node --test $(COLOR_BENCH_DIR)/exploration/shade-*.test.mjs
color-shade-evaluate:
	@node $(COLOR_BENCH_DIR)/exploration/shade-evaluate.mjs $(COLOR_SHADE_ARGS)
color-shade-neutral-audit:
	@node $(COLOR_BENCH_DIR)/exploration/shade-neutral-audit.mjs $(COLOR_SHADE_ARGS)
color-dark-red-identify:
	@node $(COLOR_BENCH_DIR)/exploration/dark-red-identify.mjs $(COLOR_DARK_RED_ARGS)
color-dark-red-diagnose:
	@node $(COLOR_BENCH_DIR)/exploration/dark-red-diagnose.mjs $(COLOR_DARK_RED_ARGS)
color-quality-curve-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/quality-curve-scale.test.mjs
color-quality-curve-scale:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/quality-curve-scale.mjs $(COLOR_CUTOFF_ARGS)
color-cutoff-index:
	@node $(COLOR_BENCH_DIR)/exploration/cutoff-index.mjs $(COLOR_CUTOFF_ARGS)
color-cutoff-resume:
	@node $(COLOR_BENCH_DIR)/exploration/cutoff-resume.mjs $(COLOR_CUTOFF_ARGS)
color-cutoff-scale:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/cutoff-scale.mjs $(COLOR_CUTOFF_ARGS)
color-cutoff-heavy:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/cutoff-heavy.mjs $(COLOR_CUTOFF_ARGS)
color-cutoff-smoke:
	@node $(COLOR_BENCH_DIR)/exploration/cutoff-api-smoke.mjs
color-cutoff-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/cutoff-*.test.mjs $(COLOR_BENCH_DIR)/exploration/methods-cutoff.test.mjs
color-cutoff-integration:
	@COLOR_CUTOFF_INTEGRATION=1 node --test $(COLOR_BENCH_DIR)/exploration/cutoff-*.test.mjs $(COLOR_BENCH_DIR)/exploration/methods-cutoff.test.mjs
color-overlap-bucket-index:
	@node $(COLOR_BENCH_DIR)/exploration/overlap-bucket-index.mjs $(COLOR_OVERLAP_ARGS)
.PHONY: color-overlap-diversity
color-overlap-diversity:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/overlap-diversity-probe.mjs $(COLOR_OVERLAP_ARGS)
color-overlap-fidelity:
	@node $(COLOR_BENCH_DIR)/exploration/overlap-fidelity.mjs
color-overlap-index:
	@node $(COLOR_BENCH_DIR)/exploration/overlap-index.mjs $(COLOR_OVERLAP_ARGS)
color-overlap-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/overlap*.test.mjs $(COLOR_BENCH_DIR)/exploration/methods-overlap.test.mjs
color-overlap-integration:
	@COLOR_OVERLAP_INTEGRATION=1 node --test $(COLOR_BENCH_DIR)/exploration/overlap*.test.mjs $(COLOR_BENCH_DIR)/exploration/methods-overlap.test.mjs
color-overlap-scale:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19217 node $(COLOR_BENCH_DIR)/exploration/overlap-scale.mjs $(COLOR_OVERLAP_ARGS)
color-overlap-inspector:
	@node $(COLOR_BENCH_DIR)/exploration/overlap-inspector-cli.mjs
color-overlap-inspector-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/overlap-inspector-server.test.mjs
color-overlap-inspector-smoke:
	@node $(COLOR_BENCH_DIR)/exploration/overlap-inspector-smoke.mjs
color-overlap-inspector-browser-check:
	@agent-browser --session overlap-inspector-t3code-28be15f7 $(COLOR_OVERLAP_BROWSER_COMMAND)
color-histogram-inspector:
	@node $(COLOR_BENCH_DIR)/exploration/histogram-inspector-cli.mjs
color-histogram-inspector-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/histogram-inspector*.test.mjs
color-histogram-inspector-integration:
	@COLOR_HISTOGRAM_INSPECTOR_INTEGRATION=1 node --test $(COLOR_BENCH_DIR)/exploration/histogram-inspector*.test.mjs
color-histogram-inspector-browser-check:
	@agent-browser --session histogram-inspector-t3code-28be15f7 $(COLOR_HISTOGRAM_BROWSER_COMMAND)
color-histogram-inspector-smoke:
	@node $(COLOR_BENCH_DIR)/exploration/histogram-inspector-smoke.mjs
color-exploration-corpus-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/corpus.test.mjs
color-exploration-browser-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/browser.test.mjs

check-types: crap-check-types
	@$(TURBO) run check-types

# CI/Local Parity commands
check-types-force: crap-check-types
	@$(TURBO) run check-types --force

ci: crap-check-types
	@$(MAKE) sandcastle-test
	@$(MAKE) sandcastle-check-types
	@$(MAKE) storage-infra-test
	@echo "Running full CI checks locally..."
	@set -e; \
	start_time=$$(date +%s); \
	$(TURBO) run build lint check-types test:unit test:integration; \
	$(TURBO) run test:e2e --concurrency=1; \
	pnpm coverage:merge; \
	end_time=$$(date +%s); \
	duration=$$((end_time - start_time)); \
	echo ""; \
	echo "✓ All CI checks passed in $${duration}s"; \
	echo "✓ Coverage report: coverage/lcov.info"

ci-force: crap-check-types
	@$(MAKE) sandcastle-test
	@$(MAKE) sandcastle-check-types
	@$(MAKE) storage-infra-test
	@echo "Running full CI checks locally (no cache)..."
	@set -e; \
	start_time=$$(date +%s); \
	$(TURBO) run build lint check-types test:unit test:integration --force; \
	$(TURBO) run test:e2e --concurrency=1 --force; \
	pnpm coverage:merge; \
	end_time=$$(date +%s); \
	duration=$$((end_time - start_time)); \
	echo ""; \
	echo "✓ All CI checks passed in $${duration}s"; \
	echo "✓ Coverage report: coverage/lcov.info"

# Clean generated artifacts
clean:
	@echo "Cleaning node_modules..."
	@rm -rf node_modules apps/*/node_modules packages/*/node_modules experiments/*/node_modules
	@echo "Cleaning compiled output..."
	@rm -rf apps/*/dist apps/docs/.next packages/*/dist packages/react-muuri/storybook-static
	@echo "Cleaning turbo caches..."
	@rm -rf .turbo apps/*/.turbo packages/*/.turbo
	@echo "Cleaning coverage reports..."
	@rm -rf coverage apps/*/coverage packages/*/coverage
	@echo "Cleaning TypeScript incremental build cache..."
	@find . -name "*.tsbuildinfo" -not -path "*/node_modules/*" -delete
	@echo "Cleaning generated OpenAPI specs..."
	@rm -f apps/ingestor/swagger.json apps/media/swagger.json apps/user/swagger.json
	@echo "✓ Clean complete"

.PHONY: color-global-bounded-probe
color-global-bounded-probe:
	@node $(COLOR_BENCH_DIR)/global-bounded.mjs --probe

.PHONY: color-global-joint-bounded-probe
color-global-joint-bounded-probe:
	@node $(COLOR_BENCH_DIR)/global-joint-bounded.mjs --probe

.PHONY: color-global-multi-prepare color-global-multi-probe
color-global-multi-prepare: color-benchmark-corpus
	@$(COLOR_BENCH_TS) $(COLOR_BENCH_DIR)/global-multi-prepare.mjs

color-global-multi-probe:
	@node $(COLOR_BENCH_DIR)/global-multi.mjs --probe

# Read-only planner experiment; requires the existing frozen million-document index.
.PHONY: color-global-planner
color-global-planner:
	@node $(COLOR_BENCH_DIR)/global-planner-evaluate.mjs

.PHONY: color-favorite-compiled-encoder-test color-favorite-compiled-encoder-benchmark
color-favorite-compiled-encoder-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-compiled-encoder.test.mjs
color-favorite-compiled-encoder-benchmark:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-compiled-encoder.mjs --benchmark $(COLOR_FAVORITE_ARGS)

.PHONY: color-favorite-compiled-index-test color-favorite-compiled-index
color-favorite-compiled-index-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-compiled-index.test.mjs
color-favorite-compiled-index:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-compiled-index.mjs $(COLOR_FAVORITE_ARGS)

.PHONY: color-favorite-preset-workload-test
color-favorite-preset-workload-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-preset-workload.test.mjs

.PHONY: color-linked-strictness-test color-linked-strictness-index color-linked-strictness-lab-test color-linked-strictness-verify color-linked-strictness-feedback-test
color-linked-strictness-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/linked-strictness.test.mjs $(COLOR_BENCH_DIR)/exploration/linked-strictness-index.test.mjs
color-linked-strictness-index:
	@node $(COLOR_BENCH_DIR)/exploration/linked-strictness-index.mjs $(COLOR_FAVORITE_ARGS)
color-linked-strictness-lab-test:
	@node --check $(COLOR_BENCH_DIR)/exploration/web/favorite-lab/strictness.js
	@node --test $(COLOR_BENCH_DIR)/exploration/linked-strictness-lab.test.mjs
color-linked-strictness-verify:
	@COLOR_EXPLORATION_OPENSEARCH=http://127.0.0.1:19216 node $(COLOR_BENCH_DIR)/exploration/linked-strictness-verify.mjs $(COLOR_FAVORITE_ARGS)
color-linked-strictness-feedback-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/linked-strictness-feedback.test.mjs

.PHONY: color-favorite-multiplicity-test color-favorite-multiplicity-fidelity-test color-favorite-multiplicity-fidelity
color-favorite-multiplicity-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-multiplicity-utilities.test.mjs $(COLOR_BENCH_DIR)/exploration/favorite-multiplicity-adapter.test.mjs $(COLOR_BENCH_DIR)/exploration/favorite-multiplicity-feedback.test.mjs
color-favorite-multiplicity-fidelity-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-multiplicity-fidelity.test.mjs
color-favorite-multiplicity-fidelity:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-multiplicity-fidelity.mjs $(COLOR_FAVORITE_ARGS)

.PHONY: color-favorite-multishard-fidelity-test color-favorite-multishard-fidelity
color-favorite-multishard-fidelity-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-multishard-fidelity.test.mjs
color-favorite-multishard-fidelity:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-multishard-fidelity.mjs $(COLOR_FAVORITE_ARGS)

.PHONY: color-favorite-performance-test
color-favorite-performance-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-performance.test.mjs

.PHONY: color-favorite-multiplicity-feedback
color-favorite-multiplicity-feedback:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-multiplicity-feedback.mjs $(COLOR_FAVORITE_ARGS)

.PHONY: color-favorite-transport-diagnostic-test color-favorite-transport-diagnostic
color-favorite-transport-diagnostic-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-transport-diagnostic.test.mjs
color-favorite-transport-diagnostic:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-transport-diagnostic.mjs $(COLOR_FAVORITE_ARGS)

.PHONY: color-favorite-pooled-test
color-favorite-pooled-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-pooled-delete.test.mjs $(COLOR_BENCH_DIR)/exploration/favorite-pooled-utilities.test.mjs

.PHONY: color-favorite-pooled-fidelity-test color-favorite-pooled-fidelity
color-favorite-pooled-fidelity-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-pooled-fidelity.test.mjs
color-favorite-pooled-fidelity:
	@node $(COLOR_BENCH_DIR)/exploration/favorite-pooled-fidelity.mjs $(COLOR_FAVORITE_ARGS)

.PHONY: color-favorite-pooled-adapter-test
color-favorite-pooled-adapter-test:
	@node --test $(COLOR_BENCH_DIR)/exploration/favorite-pooled-adapter.test.mjs
