import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { createRouter, RouterProvider } from '@tanstack/react-router';
import { ThemeProvider } from '@/components/theme-provider';
import { UploadQueueToastManager } from '@/components/upload/upload-queue-toast-manager';
import { Toaster } from '@/components/ui/sonner';
import { UploadQueueProvider } from '@/contexts/upload-queue-context';
import { routeTree } from './routeTree.gen'; // Auto-generated by TanStack Router plugin

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000 * 60, // 1 minute - data stays fresh for 1 min
      gcTime: 1000 * 60 * 5, // 5 minutes - cache garbage collection
      refetchOnWindowFocus: false, // Don't refetch when window regains focus
    },
  },
});

const router = createRouter({
  routeTree,
  context: {
    queryClient,
  },
  defaultPreload: 'intent', // Prefetch routes on hover/focus
});

// Register router type for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

function App() {
  return (
    <ThemeProvider defaultTheme="system" storageKey="wallpaperdb-theme">
      <QueryClientProvider client={queryClient}>
        <UploadQueueProvider>
          <RouterProvider router={router} />
          <UploadQueueToastManager />
          <Toaster />
          <ReactQueryDevtools initialIsOpen={false} />
        </UploadQueueProvider>
      </QueryClientProvider>
    </ThemeProvider>
  );
}

export default App;
