"""Analytic outer bounds remain separate from native conversion qualification."""
import copy
import json
from pathlib import Path
import shutil
import tempfile
import unittest
from unittest.mock import patch

import numpy as np

import avif


class ComponentBoundTests(unittest.TestCase):
    def test_shared_offset_contradiction_requires_both_directions_and_positive_weights(self):
        from iso_global_offset_bound import shared_offset_bound
        bases = [[2.9552738641205223, 3.096608370034917, 2.9552738641205223],
                 [3.3930938421523202, 2.818438746028083, 2.0874920411071076]]
        refs = [[[0, 0, 0], [0, 0, 0], [0, .16628398001194, 0]],
                [[3.672389030456543, 3.1140284538269043, .5423629879951477],
                 [1.9613218307495117, 1.2131978273391724, 0], [0, 0, 0]]]
        weights = [.17786073385939657, .7114429354375863, 1]
        actual = shared_offset_bound(bases, refs, weights)
        self.assertTrue(actual['contradiction_established'])
        self.assertAlmostEqual(actual['contradiction_margin_nits'], 1.295977276613153, places=10)
        self.assertAlmostEqual(actual['B2_implied_upper_nits'], .05429370268226785, places=10)
        self.assertGreater(actual['A_positive_gain_direction_margin_nits'], 0)
        self.assertGreater(actual['B_negative_gain_direction_margin_nits'], 0)
        constant = shared_offset_bound(np.ones((2, 3)), np.ones((2, 3, 3)), weights)
        self.assertFalse(constant['contradiction_established'])
        for invalid in ([0, .7, 1], [.2, .2, 1], [.7, .2, 1], [.2, .7, 1.1], [.2, .7, float('nan')]):
            with self.subTest(weights=invalid), self.assertRaises(ValueError):
                shared_offset_bound(bases, refs, invalid)

    def test_known_pq_white_and_black_component_enclosure_use_actual_itp_scaling(self):
        from iso_global_offset_bound import component_bounds, itp_to_p3
        # ST2084 at203cd/m2, with neutral ITP chroma. This is not a gain-map
        # reference generated by the candidate under test.
        np.testing.assert_allclose(itp_to_p3([.5806888810416109, 0, 0]), [203]*3, atol=1e-8)
        bound = component_bounds([0, 0, 0])
        np.testing.assert_equal(bound['rgb_nits_low'], [0, 0, 0])
        np.testing.assert_allclose(bound['rgb_nits_high'],
            [.014263228696628836, .006532658860476874, .007285863080226084], atol=1e-12)
        self.assertEqual(bound['delta_e_gate'], 8)
        self.assertEqual(bound['itp_ball_radius'], 8/720)

    def test_invalid_color_inputs_and_missing_report_fields_reject(self):
        from iso_global_offset_bound import component_bounds, itp_to_p3, run
        for sample in ([float('nan'), 0, 0], [0, float('inf'), 0], [-.01, 0, 0], [0, 0]):
            with self.subTest(sample=sample), self.assertRaises(ValueError):
                component_bounds(sample)
        for sample in ([float('nan'), 0, 0], [2, 0, 0], [0, 0]):
            with self.subTest(itp=sample), self.assertRaises(ValueError):
                itp_to_p3(sample)
        with tempfile.TemporaryDirectory() as directory, self.assertRaises(ValueError):
            run(directory, map_code_report={})


class GlobalOffsetNativeTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        from iso_global_offset_bound import run
        cls.temporary = tempfile.TemporaryDirectory()
        cls.addClassCleanup(cls.temporary.cleanup)
        cls.folder = Path(cls.temporary.name)
        cls.report = run(cls.folder/'standalone')
        cls.map_report = json.loads((cls.folder/'standalone/map-code-bound/results.json').read_text())

    def test_native_bound_recomputes_hashed_scalar_inputs_and_persists_narrow_evidence(self):
        report = self.report
        self.assertEqual(report['status'], 'diagnostic_only')
        self.assertNotIn('cases', report)
        self.assertTrue(all(report['validation_checks'].values()))
        self.assertEqual([row['base_codes'][1] for row in report['inputs']], [69, 67])
        self.assertTrue(report['analytic_bound']['contradiction_established'])
        self.assertAlmostEqual(report['analytic_bound']['contradiction_margin_nits'], 1.295977276613153, places=10)
        self.assertEqual(report['fixed_maximum_gate'], 8)
        self.assertEqual(report['bindings']['output']['sha256'],
                         '64e1627f20632239fa5755908bb72a4e359776c0891df92fd8b99c6b99df1091')
        self.assertEqual(report['numeric_controls']['role'], 'Implementation sanity checks only; not the enclosure proof')
        self.assertTrue(report['numeric_controls']['passed'])
        self.assertTrue(report['commands'])
        self.assertTrue(report['map_code_provenance']['commands'])
        for name, sha in report['source_hashes'].items():
            self.assertEqual(avif.digest(Path(__file__).with_name(name)), sha)
        self.assertEqual(json.loads((self.folder/'standalone/results.json').read_text()), report)

    def test_reused_native_report_has_identical_bound_with_fresh_readback(self):
        from iso_global_offset_bound import run
        actual = run(self.folder/'reused', map_code_report=self.map_report)
        for key in ('inputs', 'analytic_bound', 'numeric_controls', 'icc', 'iso_metadata'):
            self.assertEqual(actual[key], self.report[key])
        self.assertTrue(actual['commands'])
        self.assertLess(len(actual['commands']), len(self.report['commands']))
        self.assertFalse(any(any(str(arg).startswith('pack') or arg == 'compute' for arg in row['argv'][1:])
                             for row in actual['commands']))

    def test_cached_metadata_samples_hashes_and_required_provenance_cannot_be_substituted(self):
        from iso_global_offset_bound import run
        def change_base(report):
            report['records'][0]['base_nits'][1] += 1
        def change_reference(report):
            report['records'][1]['references_nits'][0][1] += 1
        def change_gamma(report):
            report['iso_metadata']['channels'][0]['gamma'] = 2
        def change_icc(report):
            report['icc']['gammas'][0] = 2.2
        mutations = [change_base, change_reference, change_gamma, change_icc,
            lambda value: value.pop('native_binary_sha256'),
            lambda value: value.update(native_binary_sha256={}),
            lambda value: value['native_binary_sha256'].pop(next(iter(value['native_binary_sha256']))),
            lambda value: value['source_hashes'].pop('appearance.py'),
            lambda value: value.update(capacity_provenance={}),
            lambda value: value['capacity_provenance'].update(native_hashes='changed'),
            lambda value: value['bindings'].pop('source'),
            lambda value: value['bindings'].update(icc_sha256='0'*64),
            lambda value: value['bindings'].update(base_coding_sha256='0'*64),
            lambda value: value['bindings'].update(map_coding_sha256='0'*64),
            lambda value: value['records'][0].update(boost_order=[16, 2, 64]),
            lambda value: value['records'][0].update(xy=[0, 0])]
        for index, mutate in enumerate(mutations):
            modified = copy.deepcopy(self.map_report)
            mutate(modified)
            directory = self.folder/f'rejected-{index}'
            with self.subTest(index=index), self.assertRaises(ValueError):
                run(directory, map_code_report=modified)
            self.assertFalse((directory/'results.json').exists())

    def test_actual_reference_substitution_rejects_even_with_updated_declared_hash(self):
        from iso_global_offset_bound import run
        modified = copy.deepcopy(self.map_report)
        entry = modified['bindings']['references']['2']
        changed = self.folder/'substituted-reference.f64'
        shutil.copyfile(entry['path'], changed)
        with changed.open('r+b') as stream:
            stream.write(np.array([1], dtype='<f8').tobytes())
        entry.update(path=str(changed), sha256=avif.digest(changed))
        with self.assertRaisesRegex(ValueError, 'reference hash'):
            run(self.folder/'reference-rejected', map_code_report=modified)

    def test_real_decoder_boundary_file_drift_cannot_publish_a_bound(self):
        import iso_global_offset_bound as bound
        directory = self.folder/'drifting-map'
        original_decode = bound.gainmap_sdr.decode
        def real_decode_then_change_extracted_map(*args, **kwargs):
            actual = original_decode(*args, **kwargs)
            with (directory/'output-inspection/map.jpg').open('ab') as stream:
                stream.write(b'diagnostic-tamper')
            return actual
        with patch.object(bound.gainmap_sdr, 'decode', side_effect=real_decode_then_change_extracted_map):
            with self.assertRaisesRegex(ValueError, 'Changed diagnostic input'):
                bound.run(directory, map_code_report=self.map_report)
        self.assertFalse((directory/'results.json').exists())


if __name__ == '__main__':
    unittest.main()
